templates/install-doped.css

This is just a minor aesthetic change, but it always annoyed me when I installed ampache. 
I also cleaned up the indentation in install-doped.css

Add 10px margin to the bottom of the install page

---

templates/show_add_shout.inc.php
themes/reborn/templates/default.css

This addresses issue #656.
jQuery-mediaTables (for some reason) was stopping the shoutbox from showing. It  turns out that mediaTables makes no difference to the shoutbox, so the simple solution is not to use mediaTables for it.

Fix shoutbox not displaying (#656)

---

config/ampache.cfg.php.dist
lib/class/preference.class.php
lib/class/vainfo.class.php

This is the first stab at adding support for additional ID3v2 genre delimiters.
I've seen in other places in the code that config checking (in this case using isset and is_array) is not done - I don't know if this is done somewhere else. So this code could be slimmed down a bit.
I've used the following files to test the code:
http://www.filedropper.com/additionalid3v2genredelimitertest
Unfortunately, I don't know how representative that test is.
I'd really appreciate, if someone with that issue could test it.

Added support for additional ID3v2 genre delimiters.

---

nbproject/project.properties
scripts/hooks/pre-commit

I created a Git hook for me because I have some problems to get the coding guidelines to my code.
It just checks all files you want to commit before you can write a commit message.
I just throw it in here, maybe someone can use it :-)
At this time it is only partially useful because a lot of files have already issues. When I execute scripts/tests/codestyle.sh I get problems on ~260 files. Maybe we can fix this soon, so anyone that is not used to this syntax can rely on some scripts.
I also change the Netbeans project properties from time to time to get it closer to psr-2, so php-cs-fixer does not have to complain :-)
It is still not perfect, but we are getting closer with the Netbeans code formatter.
EDIT: Just for showcase, it gives you something like this when you hit git commit: …

Git helper for Coding standard

---

lib/class/stream_playlist.class.php

reason: http://support.microsoft.com/kb/288102/en-gb
Windows Media Player is going to play a playlist as wmv file, and fail.

Fix Content-Type of asx

---

lib/class/subsonic_api.class.php

Need to pass through the http status code from the underlying request in order to properly answer with a 206 when skipping bytes.  This needs to go here because this is where the response body starts, so setting it later won't work.
This will fix issues with gstreamer where it reported that ampache couldn't seek because of the 200 response code that was previously being returned.  I've also tested that seeking still works in VLC with this.

Set http status code from the curl request

---

themes/reborn/templates/default.css

Reverts ampache/ampache#769
Doesn't resolve the problem, we need to think about "Fix header/sidebars position on compatible themes" option which is often used ;)
We just need to override the top position when "fixedrightbar" class is added to the rightbar. Otherwise for fixed header/rightbar, it's working great.

Revert "Solve #768"

---

README.md
lib/class/mailer.class.php

Comparisons against Booleans should use the identical operator to compare to avoid any inconsistencies or false positives. I found this issue using Code Climate to evaluate the code, so I added the Code Climate badge to the README.

Converting Boolean compare to identical operator

---

templates/show_arts.inc.php

Added "cache buster" parameter to image url in show_arts.inc.php as browsers seem to ignore cache control directives when images are inserted into DOM using javascript.
I believe this resolves issue #840.

Stop image caching in art selection

---

locale/base/messages.pot
locale/base/translation-words.txt

I've updated them to match the latest state.
I also changed the auto-update link in Transifex to match the RAW-messages.pot file on GitHub as described in the Transifex docs. So this is also a test for Transifex if it automatically pulls the latest version after merge.
@Afterster, have you changed the preference IDs in the DB?
You see that I had to rewrite many of the IDs in the DB-W.txt, and check if they match the DB-entries. 
This needs a lot of time, because it have to be done manually at the moment.
I thought, that the IDs do not change if you add preferences, so I used them as a fix point, so that I only have to check which prefs are gone and which are new and update only these.
Otherwise if they are generated automatically in any situation, I maybe should update the …

Base database-words.txt and translation catalog updated

---

lib/class/song.class.php
lib/class/webplayer.class.php

This patch enables playback of *.opus files in the web player (tested with current versions of firefox and chrome).

Improved support for the opus audio format

---

sql/ampache.sql

Missing semicolon halts install/update, MariaDB 5.5.2

Missing semicolon halts install/update, MariaDB 5.5.2

---

bin/calculate_art_size.inc
lib/class/art.class.php

calculate_art_size does not have into account the new possibility ampache has to store metadata on disk. With this changes this binary works again.

Fix calculate_art_size binary so that it works with new configurations

---

lib/class/catalog.class.php
lib/class/vainfo.class.php
modules/catalog/local.catalog.php

Add function to set song rating based on POPM id3 tag when create or update catalog (resolve ampache/ampache#919)
If no Ampache user mail matches with the one in POPM mail, use super user rating (id = -1)
Change-Id: I83b94153655ab21d8dede3cade4fb260459df3c3
Signed-off-by: nioc <nioc@users.noreply.github.com>

Add rating based on POPM id3 tag

---

templates/show_localplay_status.inc.php

Not a big deal. In localplay playlist, current song & album were not separated.

Add missing separator between track & album in localplay playlist

---

lib/class/ui.class.php

Added missing space between the entered CSS class attribute and the next attribute in that tag.
This is mostly cosmetics (browsers can handle this mistake), but it is marked as "broken" when looking at the page source in FireFox.

Fixed missing space in get_icon method when using sprites

---

lib/class/stream_playlist.class.php
lib/class/stream_url.class.php
lib/class/update.class.php
sql/ampache.sql

* New column 'track_num' added to table stream_playlist
* Added new item 'track_num' to properties array within Stream_URL
* Added track number for xspf playlist format
xspf playlist generation now includes track numbers (if track numbers are included in the song) for streaming. This functionality should be feasible to add to other playlist formats provided the playlist supports track numbering.

Added functionality for streaming playlists to support track numbers

---

lib/class/vainfo.class.php

Patch which fixes the wrong size saved in database, as discussed in Ticket #912.
In short, Ampache stores the file size as found in some id3v2 tags. I have some songs which contains a "size" frame in the comment area of the id3v2 tag. Sadly the saved size is not the real file size, which could cause the song to stop playing too early when listening through Ampache.
I'm not sure if this patch is the ultimate solution. It works for me, but it may not work if the catalog is remote or something like that.
As I only have local catalogs, I cannot test it with other options.

Patch for wrong file size in database

---

lib/class/catalog.class.php
lib/class/subsonic_api.class.php
lib/class/subsonic_xml_data.class.php

- Make Catalog::get_artists return an album count as "albums".
- Pass through to subsonic api calls to avoid running query for every
artist to count albums (as was happening previously)

Speed up (a lot) subsonic getArtists method

---

lib/class/search.class.php

This makes it possible to search for rating < 1 to build a smart
playlist of unrated songs. Fixes #819.
Signed-off-by: Byron Marohn <combustible@live.com>

Make unrated songs appear as 0 rating

---

config/ampache.cfg.php.dist
lib/class/scrobbler.class.php
lib/class/userflag.class.php
lib/preferences.php
modules/plugins/Lastfm.plugin.php
modules/plugins/Librefm.plugin.php
preferences.php

Upgrade the scrobbler class, Lastfm and Librefm plugins to use the new API.
Authentication is changed:
-admin needs to create a last.fm API account, set their API key and secret in the ampache.cfg file,
-users need to grant Ampache application to last.fm / Libre.fm services by using preference tab > plugins.
Resolves ampache/ampache#922
Add the "spread the love" function to share your favorites on Last.fm and Libre.fm.
Change-Id: Ia81334f4f4506258a27d40b6c257a1e38bd69097
Signed-off-by: nioc <nioc@users.noreply.github.com>

Upgrade scrobbling API (last.fm and libre.fm)

---

lib/class/subsonic_api.class.php

In comparsion with the original subsonic API, the implementation of Ampache does not honor the *Count= parameter if it is set to 0.
When using original subsonic with a query like:
```
http://demo.subsonic.org/rest/search2.view?u=guest1&p=guest&c=nothing&v=1.8.0&query=bilk&albumCount=0&songCount=0
```
The result is a list containing just one artist:
```xml
<subsonic-response status="ok" version="1.13.0">
<searchResult2>
<artist id="8" name="bilk"/>
</searchResult2>
</subsonic-response>
```
When using this parameters with ampache, you get a complete list of songs, albums, artists matching your search term:
```
http://localhost/rest/search2.view?v=1.8.0&c=sampleClient&u=apiuser&p=veryStrongPassword&query=ACDC&albumCount=0&songCount=0
```
```xml
<subsonic-response type="ampache" …
```

Subsonic API: search2 ignores song/artist/albumCount = 0

---

lib/class/api.class.php

This allows using the xml api with the full advanced search possibilities.  It does require understanding how the parameters relate to the search performed however, which requires looking at the code.  Something more self documenting would be more code, but easier to use.  Another option would be adding some documentation to the wiki detailing the possible parameters to this call.

Add advanced_search api call

---

lib/class/subsonic_api.class.php

When trying to get an cover art using the Subsonic API implementation, no image is delivered if the given ID is a song ID.
In the subsonic API docs is defined, that you can call getCoverArt with an ID which is either an albumID, artistID or songID.
When doing this with ampache, you only get a cover art when using the album ID.
This is caused by the SQL query generated in Art()->get_db(). 
The query tries to find images in the image table with 'kind' = "song" and the song ID.
I guess most of the time, there is no entry for 'kind' = 'song' (or for the song ID), because the cover art is the same as for the album to which the song belongs.
So that information is only available when querying with 'kind' = 'album' and the proper album ID.
To work around that behaviour, I implemented a second …

Subsonic API Impl: Deliver album art if the song does not have a custom picture

---

config/ampache.cfg.php.dist
lib/class/stream.class.php
lib/class/update.class.php
lib/init.php
lib/preferences.php

config/ampache.cfg.php.dist
+ updated version because the changes depend on database and base code
changes
+ renamed variable `%SAMPLE%` -> `%BITRATE%`
lib/class/stream.class.php
+ changed `AmpConfig::get('sample_rate');` ->
`AmpConfig::get('transcode_bitrate');` due to db changes
+ renamed variable `%SAMPLE%` -> `%BITRATE`
+ renamed variable `$sample_rate` -> `$bit_rate`
+ renamed variable `$user_sample_rate` -> `$user_bit_rate`
lib/class/update.class.php
+ New update function to change preference name `sample_rate` ->
`transcode_bitrate`
lib/init.php
+ changed config file version for config autoupdate
lib/preference.php
+ changed case `sample_rate` -> `transcode_bitrate` due to db changes
I hope, I didn't forge anything in the source.
I've tested webplayer and streaming. Works as …

Wrong named sample rate variables fixed + config and db update

---

composer.json
lib/class/DatabaseObject.php
lib/class/Interfaces/Model.php
lib/class/Metadata/Metadata.php
lib/class/Metadata/Model/Metadata.php
lib/class/Metadata/Model/MetadataField.php
lib/class/Metadata/Repository/Metadata.php
lib/class/Metadata/Repository/MetadataField.php
lib/class/Repository.php
lib/class/catalog.class.php
lib/class/search.class.php
lib/class/song.class.php
modules/catalog/local/local.catalog.php
scripts/hooks/pre-commit

Hi again
This one fixes the errors introduced with the Metadata feature.
Main changes:
- Switch class loading to composer (psr-4). The old classloader was still working somehow (at least the import still worked for me), but the composer one threw errors.
- Fixed some typehints and similar stuff. Probably introduced this when I refactored some of my code.
- Improved filtering of metadata. The old one was not working as intended because I did something stupid...so just all data got imported. If you already imported songs with the new metadata feature, you could just truncate the `metadata` and `metadata_field` tables and update your library.
- updated needed PHP version to PHP 5.4 because this feature is using traits
Please make sure to run a `composer dumpautoload` after checking out the …

Fix metadata errors

---

README.md

I saw it on the Owncloud Readme. It's an on-click-live-chart service from Transifex also if I didn't saw it in their docs. So I adapted it to fit our translations progress.
It also makes the manual updating of the currently supported languages unnecessary.
And a small typo fix.
The last PR for me this Year.
**May your wishes come true,**
**and everything bad stay away from you!** :tada:
Best wishes
Psy-Virus

Added Graphical overview of translation progress

---

lib/class/subsonic_api.class.php

Subsonic clients (at least dsub) appears to expect all starred artists, albums and tracks to be returned when requesting a list of starred items. Ampache was returning only 10, which broke starred functionality in dsub. This changes the subsonic API class to return up to 99 999 items of each type instead, enabling starred functionality to work properly.
I have tested the change using dsub as a client to ampache.

Return up to 99 999 starred artists/albums/tracks to subsonic

---

config/ampache.cfg.php.dist
lib/class/ampconfig.class.php
lib/class/auth.class.php
lib/class/ldap.class.php

What have been done:
- Ignore `composer.lock` files
- Add a default value to `AmpConfig::get`.
The default behaviour is still the same: `AmpConfig::get($key)` returns the value associated to the given key, and `null` if the key doesn't exist.
But you can now provide a default return value: `AmpConfig::get($key, $default)` returns the value associated to the given key, and `$default` if the key doesn't exist.
- Rework LDAP section in config file
This section should be a little cleaner, but might need more documentation.
- Rework LDAP auth
- Move it from `lib/class/auth.class.php` (`Auth::ldap_auth`) to `lib/class/ldap.class.php` (`LDAP::auth`). The parameters are the same, but the function has been fully rewriten:
- Code cleanup (in particular, no nested ifs anymore...)
- Parameter for …

Rework LDAP Auth

---

server/sse.server.php

Otherwise chrome complains with:
EventSource's response has a charset ("iso-8859-1") that is not UTF-8. Aborting the connection.
Solves issue [#1162](https://github.com/ampache/ampache/issues/1162)

Specify utf-8 charset for event-stream content to make Chrome happy

---

lib/class/webplayer.class.php

IRC backlog:
Niols │ Hey, the player time bar isn't working on my instance, is this due to a recent commit (I'm up-to-date with develop) or is it only me?
@Afterster │ working on my side
@Afterster │ maybe related to your transcoding config
Niols │ Oh
Niols │ That would explain a lot of things actually if transcoding weren't working ^^
Niols │ How can I know if transcoding is working correctly?
@Afterster │ I think it is working by default now, and it's why you don't have the time (it's generally the case when you transcode)
Niols │ That's sad :(
Niols │ Hm, about transcoding, it looks like I can't transcode FLAC files
Niols │ I looked at the configuration, and I don't seem to have anything related to transcoding of FLACs specifically
Niols │ Except 'transcode_flac = allowed'
@Afterster │ …

Fix issue that blocks webplayer when transcoding

---

.tx/config

To make it work right with, for example, the CLI client, it's easier to change it to the real Transifex behaviour so that the source language is ignored if you pull/push the files.
The file_filter seems to use the `<lang>` expression as a wild card.
On my tests with the CLI Client, it worked perfectly with one `<lang>` expression to get the right language code from Transifex, if it is set up properly on Transifex. (`locale/languagecode_LANDCODE/messages.*`)
Now the .tx config should fit the Ampache project. Maybe here was one of the problems, why it wasn't working with the Amazon instance?
Well @Afterster, I don't know how it was tested, so it's only a shot into the blue. :-)
By the way, I also didn't get it really working, for my taste, too less examples or bad documented, idk.. -.-
But …

Transifex config update

---

lib/preferences.php

It's always better to keep those variable user-, plugin-, etc-names as dynamic as possible. Otherwise it's sometimes extremely problematic to find the right sentence-formatting. In German I would translate it that way:
"Klicke um `$plugin_name` den Zugriff zu erlauben"
And does this English sentence in the source fit better? As I see from the context, the user is asked to give `$plugin_name`the right to access Ampache, is this right?
:-)

A small change to make translation easier

---

lib/class/autoupdate.class.php
templates/header.inc.php
themes/reborn/templates/default.css

FIX for #1195: file path correction.
New position for update notification:
Since ever, I hated it that the Update notification is within the headerbox. Now it's on the top of the content div like the "updated config" notification.
I also kicked out one permission check so the "autoupdate" notification and/or the "new config" notification is only shown if the permission is 100... Like before but in another way. ^^
Before, there was a `<span>...</span>`, no matter what user was logged in. Now there is a div with `id="update_notify"` what is also only shown, if the admin is logged in.
And it looks much cleaner on the UI. :-)
I also cleaned the depending CSS rule in `/reborn/templates/default.css`

FIX for #1195 & New position for update notification

---

lib/class/catalog.class.php

Whereas the gathering art process returns several images url, then it only tries to insert the first image. 
If the image doesn't meet the dimensions configured, the next ones are not tested and no image is selected.
This case is very frequent with LastFm gathering and art minimal size configured, as LastFm returns several images from the the smallest (34x34) to the largest. Setting art minimal size over 34x34 leads to retrieving no images.
The provided fix tests all the images returned till it finds a valid one into the configured dimensions.
It can now select larger images from LastFm according to the following configuration:
```
; Art Gather Order
; Simply arrange the following in the order you would like
; ampache to search. If you want to disable one of the search
; methods simply …
```

fix: Test all images found to select the one with the good dimensions

---

lib/class/xml_data.class.php

The Ampache-XML API was not returning a valid XML document in case of failed passphrase validation.
Closes #1242.

Fix proposition for #1242

---

lib/class/query.class.php
templates/show_song_row.inc.php

Remove leading character for BOM for some files that were using it. With this PR, all the files in Ampache should be encoded as UTF-8 without BOM.
This is to solve an issue discussed on IRC, which arised in https://github.com/ampache/ampache/issues/1249 resulting in invalid JSON output.

Use UTF-8 without BOM for all the files in Ampache

---

lib/class/subsonic_xml_data.class.php
modules/catalog/local/local.catalog.php
modules/catalog/remote/remote.catalog.php
modules/catalog/subsonic/subsonic.catalog.php

Returns path relative to the catalog root path in Subsonic API.
<del>Note that for this I needed to implement the `Catalog::_get_info`
function, which was already called in the code, but was not declared
anywhere. This implementation may not be the best one…</del>
Closes issue #1213.

Proposition of fix for #1213

---

admin/catalog.php
lib/class/catalog.class.php
lib/i18n.php
locale/base/gather-messages.sh
playlist.php
templates/show_random.inc.php
templates/show_recently_played.inc.php

This commit introduces a `nT_` function to handle pluralization in
localizations, and avoid the need to call ngettext, which was resulting
in errors if PHP Gettext module was not available (and this was not
enforced by Ampache).
Any occurrence of `ngettext` has been replaced by this `nT_` call.
Also removed the useless keywords in the `gather-messages.sh` script,
and added the newly introduced `nT_` keyword.
Closes issue #123.

Fix proposition for issue #123.

---

lib/class/api.class.php

XML API version is now assumed to be the latest available if not
specified as a parameter. Also fix the issue that an empty XML document
was issued when the version was not specified.
Closes issue #1247.

Fix issue #1247

---

lib/class/update.class.php
sql/ampache.sql

Homogeneize `username` field length in SQL database.
Set the `VARCHAR` field used for `username` to have a maximum size of
255, which was the highest value used across the tables. This should fix
some errors with MySQL strict mode (and potentially unnoticed previous
errors).
Closes #1214.

Fix for issue #1214.

---

lib/ui.lib.php

Notification text was not correctly escaped.
Quotes were not escaped in notification text, which resulted in
JavaScript errors with some translations, such as French translation,
which make heavy use of quotes.
Closes #1259.

Fix issue #1259.

---

templates/show_html5_player.inc.php

Aurora.JS was included, but we were not including the codecs JS files.
Including them fix the impossibility to play OGG vorbis audio files when
HTML5 player is disabled and only Flash player and Aurora.JS are
enabled.
**Important note**: Progression bar was not working even if the file was playing nicely. There might still be an underlying issue, that I did not find yet. I think we should open a new issue to track it and remember to fix it, if you think this change can be merged.
Closes #1250.

Fix for #1250

---

install.php
lib/class/core.class.php
lib/general.lib.php
templates/show_install_config.inc.php

Generate `sceret_key` on Ampache installation
Generate a `secret_key` on Ampache installation and put it in the
generated config. This removes the need to do it manually, and the
secret key is ensured to be crypto safe.
Also move the `web_path` configuration setting under a "Various"
fieldset, as it had nothing to do with database settings.
Also added a comment about a missing `break` statement, which was on
purpose, but one could think it was a mistake at first sight.
Closes #1248.

Fix for issue #1248

---

modules/catalog/dropbox/dropbox.catalog.php

Copying dropbox secret key from the Dropbox UI easily adds extra
whitespaces at the beginning of the string, which leads to invalid
secret key and stack trace. As they are invalid, apply a trim to them
before storing them in database.

Apply trim on dropbox parameters

---

templates/show_pvmsgs.inc.php

Extra `public` keyword in private message templates lead to JavaScript
error.
Closes #1282.

Fix issue #1282

---

lib/preferences.php
templates/show_playlist.inc.php

Wrong gettext function calls
There were some issues when gettext is not installed on the system, due
to direct function calls to gettext and not to the encapsulated ones.
Closes #1211.

Fix issue #1211

---

templates/show_html5_player.inc.php

I hope there wasn't good reason to not enable it: woks well with Chrome

activate jplayer "preload" option

---

lib/class/catalog.class.php
modules/catalog/beets/beets.catalog.php
modules/catalog/beetsremote/beetsremote.catalog.php
modules/catalog/dropbox/dropbox.catalog.php
modules/catalog/local/local.catalog.php
modules/catalog/remote/remote.catalog.php
modules/catalog/soundcloud/soundcloud.catalog.php
modules/catalog/subsonic/subsonic.catalog.php
modules/localplay/httpq/httpq.controller.php
modules/localplay/mpd/mpd.controller.php
modules/localplay/upnp/upnp.controller.php
modules/localplay/vlc/vlc.controller.php
modules/localplay/xbmc/xbmc.controller.php
templates/show_localplay_add_instance.inc.php
templates/show_localplay_edit_instance.inc.php
templates/show_localplay_instances.inc.php

I fixed the `types` associated to modules in localplay and catalog and used them to display the correct input, with the correct type, preventing passwords from appearing in cleartext.
I also took profit of the new HTML5 types (int and url) to have a better experience on browsers which support them.
This fixes #1339.

Use correct fields type in modules and localplay

---

lib/class/api.class.php
lib/class/xml_data.class.php

Includes are specified by the `include[]` array `GET` parameter.
Supported includes as of now are:
* For `artists` and `artist` actions, you can include `albums` and/or `songs`.
* For `albums` and `album` actions, you can include `songs`.
For this purpose, I had to edit the `output_xml` method to be able to generate an XML document without any header nor footer.
I just did these four actions as they are the only one I really know at the moment, and needed includes for. I can handle includes for any other action if you think it might be interesting, or I will complete it whenever someone sees a need for it.
Note: @Afterster do you know why the methods listed above are marked as `DEPRECATED` in docstrings?

Basic include support in the XML API

---

modules/catalog/dropbox/dropbox.catalog.php
modules/catalog/local/local.catalog.php

Invalid URL type for input fields for paths
Some input fields were wrongly assigned a "url" type and browsers were
enforcing a valid URL to be put in these fields. Set them back to text.
Closes #1356.

Fix issue #1356

---

themes/reborn/templates/dark.css
themes/reborn/templates/light.css

There was a small issue with the light theme: in artist view (among others), the tabs were orange and not blue. This is a very small tweak to override the tab color in light.css and dark.css.

Minor correction to tab theming for reborn theme

---

lib/class/daap_api.class.php

i've noticed that the column composer isnt filled so i modify the daap_api.class.php and now is showing the info of composer on its respective column.

Composer info on Composer column in Itunes

---

config/ampache.cfg.php.dist

Modified the wording for the metadata config switches comment, to correct a long-standing tiny spelling mistake that had always bugged me :)

Small update to ampache.cfg.php.dist wording

---

lib/class/daap_api.class.php

With this changes now the requests of itunes shows the revision number and the session id.
Solves the Missing session id on the ampache log.
I made changes on the server_info part, based on the server_info response of the forkeed-daapd project.

Solves the Missing session ID showed on the ampache log

---

lib/class/artist.class.php

When using a non-default sort of an artists albums disk order is undefined. I was getting albums listed like this
Album A [Disk 2]
Album A [Disk 1]
Album B [Disk 1]
Album B [Disk 2]
Disk will now always sort ASC

Add sort by Disk number to all non-default sorts

---

lib/class/catalog.class.php
lib/class/vainfo.class.php

This should correctly handle removing duplicates even when v2.4 is being used. Fixes #1402

Handle ID3v2.3 and v2.4 better regarding multivalued lists

---

README.md

Since an Github Update, the localization chart wasn't displayed any more.
So I reached out to the Github support and they gave me one with less redirects.
:-)

Fixed the localization chart

---

config/ampache.cfg.php.dist

Added a line for ffmpeg opus encoding (transcoding) using libopus (which obviously needs to be installed) to transcode on the fly to the very fast and efficient opus codec. (Very personal) bitrate recommendation: 128k (To be set in the the admin interface or user personal preferences).
I'm suggesting ogg as a transport (ogg opus) which in turns requires the vsync 2 option.

Add opus transcoding arguments to ampache.cfg

---

config/ampache.cfg.php.dist

I suggest changing the default transcode target for flac from ogg (vorbis) to opus, which is now a default codec in many systems (due to it being a requirement for WebRTC, implemented by all modern browsers and mobile OSes).
The reasoning is that opus is currently our best free and open codec for low latency, high quality sound, and at 128k or below, it offers better performance than vorbis. Low bandwith, low latency and high quality is exactly a use case for Ampache transcoding, so I suggest the ampache config suggests using opus, at the very least for flac.
We could even suggest it as the basic target for encode_target, encode_player_webplayer_target and encode_player_api_target in replacement of the (aging, proprietary) mp3.

Change default flac transcode target to opus

---

config/ampache.cfg.php.dist

To make the transcoding section of ampache.cfg easier for new users, I suggest making the comments more explicit, giving short examples of why one would want to use an option, for instance.

Update ampache.conf transcoding comments

---

lib/class/user.class.php

Added test for ipv4/ipv6 addresses. Added insertion of brackets to the `parse_url` function for IPV6 addresses and removal of brackets for the `inet_pton` function.

ipv6 addresses couldn't be  added to user's ip history.

---

templates/show_login_form.inc.php
templates/show_lostpassword_form.inc.php

Hi there,
I propose to replace the autofocus JS handling by a standard one. When the page take some time to load and we already filled the login and typing the password, the focus get back to the login. With this trick, it didn't.
Thanks for this amazing piece of software, have a nice day.

JS autofocus on login and lost password pages replaced by au HTML5 attribute

---

lib/class/catalog.class.php
modules/catalog/seafile/SeafileAdapter.php
modules/catalog/seafile/composer.module.json
modules/catalog/seafile/seafile.catalog.php

Hi, I needed a way to connect Ampache to my [Seafile](https://www.seafile.com/) file server, so despite not really being a PHP developer I decided to write my own.  I based it initially off the existing Dropbox module and used [this Seafile API client](https://github.com/rene-s/Seafile-PHP-SDK). I've Added, Verified, and Cleaned multiple times and everything seems to work. Well, the "gather art" process tries to treat my fake file paths as  local paths and displays failures, however it still can gather from searches, etc.
I did make one change to the `Catalog` class itself: I wanted to be able to use the "Update from tags" feature as I was organizing my library and fixing bad tags. The Catalog class's `update_media_from_tags` function was assuming the files were local (and it being static …

Seafile Catalog Module

---

modules/catalog/dropbox/dropbox.catalog.php
modules/catalog/seafile/seafile.catalog.php
themes/reborn/templates/dark.css
themes/reborn/templates/light.css

Changed and combined some strings to make translation in Transifex
easier. It's always better to not split up translatable strings, so
translators can see how they're put together and don't have to search
for the parts.
Also, in the `dropbox.catalog.php`, I changed the strings to not behave
like html tags. Transifex doesn't like this / treats it as html tags.
;-)
If it's better, we also could change the `\'` to `"`. But I guess it doesn't really matter.
EDIT: Btw. I also put some new rules into the reborn themes CSS to highlight the links in the "add-catalog-help-section"
:-)

Small changes to make translation easier

---

lib/class/subsonic_api.class.php

The `type` in `$ids[]` is not properly assigned when `star.view` or `unstar.view` was called with `albumId` or `artistId` resulting in a `NULL` value in the `user_flag`.`object_type`-Column.

Setting favorite album or artist wont work via the Subsonic-Api

---

lib/class/subsonic_xml_data.class.php

I'm using latest Ampache (248d09e88c7e6cf0dbbe2f8872155ca212dc389b) with UltraSonic. But artist name of songs have been not displayed since the version. Because `$artistData['f_full_name']` doesn't exist.  
So I replaced `f_full_name` to `name` to fix the issue.

Fixed an issue that artist name became empty in SubsonicAPI.

---

rest/index.php

Some buggy (supposedly QT5) clients send the id parameter formatted as an IP address (sic!) to the Subsonic API.
See https://github.com/clementine-player/Clementine/issues/6080 and https://github.com/ampache/ampache/issues/1704
This workaround tries to detect that and calculate the correct song id from the parameter before passing it on.

add workaround for buggy clients

---

lib/class/search.class.php
templates/rightbar.inc.php

This part call the playlist_object.abstract.php for each playlist from everywhere. It results on User::format calls with the heavy bandwitch usage sum MySQL query.
I'm a long time Ampache user so my bandwitch usage is pretty loaded. Before using playlists, I hadn't any performance issue. I never make the link between playlist and my performance issues until today.
I didn't spend a lot of time to test my fix but didn't encounter any trouble so far.

Fix #1717 performance issues with playlist display

---

bin/fix_filenames.inc

When i ran bin/fix_filenames.inc by executing:
sudo -u wwwrun php fix_filenames.inc
i get:
Quellzeichensatz (UTF-8):                                                                                                    
Verwende UTF-8 als Quellzeichensatz                                                                                          
Prüfe  ()
Fehler: Fehler beim öffnen von 
Überprüfung der Dateinamen, auf passende Zeichen, fertig gestellt
Thats it. I guessed that fetch $row['0'] will look for column named '0' instead of column Number 0 which is named 'id'.
I changed it and it works.
So here is my Version for you to check.

Fix_Filenames: Error Opening Catalog

---

lib/class/song.class.php

There is a Bug preventing moving Songs to another album when Tag writing is enabled: As update-functions will only set db-ids to new value and will not change full qualifier names in metatags before writing, the id3 tags will still be written with old names. When reading Tags afterwards, the changes are discarded. Added format() in between update of db.ids and writing prevents this.

Bug:Moving Song to new Album + writing of Tags

---

lib/class/song.class.php

I changed the order in which the Metadata is parsed in write_id3. This will set custom fields to values of song-instance as they are defined in get_metadata, overriding them as needed. Otherwise the standard metadata like "band" will be overridden by custom value in each song that cannot be changed from edit album. So changing Albumartist wouldn't work.

Bug:Change AlbumArtist + custom metadata

---

lib/class/album.class.php
lib/class/vainfo.class.php

It may happen that Tag "Year" is not well formatted (e.g. containing -1), which would lead to DB-Error in updating the field when "Reading from Tags" is done. The cleaning routines of Album::Check were moved into this function to get this working.

Vainfo::clean_tag_info cleans year and disk

---

templates/show_users.inc.php

The user list header column is in the wrong order and also doesn't sort my username. only fullname.
this commit fixes both

fix user sorting

---

play/index.php
templates/header.inc.php
templates/rightbar.inc.php

Don't record the stats for a playback if you're requesting a download/play with cache=1
Example URL:
```
https://ampache/play/index.php?ssid=1234&type=song&oid=7873&uid=20&player=api&name=Stan%20the%20Man.mp3&cache=1
```
This is to allow API clients to use the record_play method instead:
```
https://ampache/server/xml.server.php?action=record_play&auth=1234&version=350001&type=song&id=7873&user=20
```

Allow disabling stat recording from the play url

---

lib/class/podcast_episode.class.php
lib/class/song.class.php
lib/class/video.class.php

close #1959
play_url can be called with a null player and it should fall back to an empty string.

generic_play_url should be passed a string

---

templates/show_search_form.inc.php
templates/show_stats.inc.php
templates/show_stats_highest.inc.php
templates/show_stats_newest.inc.php
templates/show_stats_popular.inc.php
templates/show_stats_recent.inc.php
templates/show_stats_userflag.inc.php
templates/sidebar_home.inc.php

I think that the sidebar should only show the "Video" header on the sidebar when the user has a video catalog with videos in it.
If you have enabled video features in Ampache server settings, then you will get the "Video" section in the sidebar, even if you do not have any video catalogs. I don't think this makes any sense, as it distracts the user by cluttering the interface with something that appears relevant, but does nothing.
This is a fairly simple fix, adding a check to see if there are any videos in the database before showing the heading.
Change with video:
Change without video:

Only show the "Video" header on the sidebar when there are videos

---

templates/show_song.inc.php

In response to #2000. It makes sense to keep the order of the play buttons consistent across the interface.

Change position of "Play next" button

---

themes/reborn/templates/default.css

Noticed on the Debug page, that if there is a really long line that it creates a scroll bar and pushes the width of the table larger than the page.
I think it should be okay to wrap very long lines so that it removes the scroll bar and keeps the page looking nice.

Allow cells in Debug page to wrap long lines

---

templates/show_album_row.inc.php
templates/show_artist_row.inc.php
templates/show_playlist_row.inc.php
templates/show_podcast_episode.inc.php
templates/show_podcast_episode_row.inc.php
templates/show_recently_played.inc.php
templates/show_song_row.inc.php
templates/show_video_row.inc.php

Looks like there were a couple more cases where play_next comes after play_last. Probably should have looked first time for #2000.
Also, for some reason and only in some cases was play_last nested within play_next (or visa-versa). So I took the liberty of just moving them out on their own, makes code look nicer and more consistent.

Fixed more occurences of play_next in wrong spot

---

templates/show_login_form.inc.php

When mailer is not enabled, the loginoptions div should not show, otherwise there is some extra padding. Also, simplified the logic for if mailer is enabled, so it doesn't have to run twice.

Fix and simplify logic for .loginoptions

---

lib/class/ui.class.php

Simplified the ternary operator, into a null coalescing operator. Also, changed the id attribute to default to "icon-$name" instead of "icon" as the class is already icon. Added the "icon-" prefix just in case there happens to be another element with the same id value. Then applied the same thing to get_image.

fixes to get_icon/image

---

templates/header.inc.php
themes/reborn/templates/dark.css
themes/reborn/templates/default.css
themes/reborn/templates/light.css

Feel free to edit as you think is necessary, but I wanted to replace the '<<<' & '>>>' for the sidebar with an icon so I moved it into the css, and since there is no icon added some logic to detect if theme doesn't provide an icon to fallback to the brackets.
Also, noticed that "Loading" wasn't being translated.

Sidebar tweak and translation add

---

lib/class/search.class.php
lib/class/song.class.php
lib/class/update.class.php
lib/class/xml_data.class.php

Set the count when you get_items for a search allowing you to use a more relevant total instead of an arbitrary limit.

Add last_count to search table

---

config/ampache.cfg.php.dist

This PR simply adds some extra information to parameter local_web_path in the default configuration file which I would have found useful when setting up ampache behind a reverse proxy.

Extend information about local_web_path for reverse proxies.

---

rest/index.php

The Subsonic API allows to ask for a given format of the response with parameter f. However if the method does not exist the server ignores the parameter f (in this case JSON):
$ curl "https://ampache.server/rest/NonExistingMethod.view?v=1.8.0&c=curl&u=user&p=enc:xxx&f=json"
<?xml version="1.0" encoding="UTF-8"?>
<subsonic-response xmlns="http://subsonic.org/restapi" status="failed" version="1.13.0"><error code="70" message="subsonic_api"/></subsonic-response>
After this commit the answer looks like this:
$ curl "https://ampache.server/rest/NonExistingMethod.view?v=1.8.0&c=curl&u=user&p=enc:xxx&f=json"
{
"subsonic-response": {
"status": "failed",
"version": "1.13.0",
"error": {
"code": 70,
"message": "subsonic_api"
}
}
}

Support returning a response in JSON format if the subsonic api method does not exist

---

lib/class/art.class.php

Two issues have been fixed:
1) The gather_musicbrainz() method didn't get the album data
2) The key used to retrieve the musicbrainz ID was wrongly "mbid",
whereas the correct is "mb_albumid"
Before the fix the log would show:
Method used: gather_musicbrainz
Method used: gather_lastfm
After the fix:
2020-01-09 00:14:22 [admin] (art.class) -> Method used: gather_musicbrainz 
2020-01-09 00:14:22 [admin] (art.class) -> gather_musicbrainz Album MBID: e7e6caa2-fd69-309a-b684-57cf8cc8b23b 
2020-01-09 00:14:24 [admin] (art.class) -> gather_musicbrainz Found ASIN: B0000089DH 
2020-01-09 00:14:24 [admin] (art.class) -> gather_musicbrainz Evaluating Amazon URL: http://ec1.images-amazon.com/images/P/B0000089DH.01.LZZZZZZZ.jpg 
2020-01-09 00:14:24 [admin] (art.class) -> gather_musicbrainz Amazon URL …

Fix the retrieval of art from musicbrainz.

---

lib/class/artist.class.php
lib/class/query.class.php

Hi @lachlan-00,
when using the current develop version I experienced an empty album list on the artist page. In the debug log the following error occurs:
` 2020-01-16 21:36:40 [xyz] (dba.class) -> Error_query SQL: SELECT MAX(``album``.``id``) AS ``id``, ``album``.``release_type``, ``album``.``mbid`` FROM ``album`` LEFT JOIN ``song`` ON ``song``.``album``=``album``.``id`` LEFT JOIN ``catalog`` ON ``catalog``.``id`` = ``song``.``catalog`` WHERE (``song``.``artist``='1234' OR ``album``.``album_artist``='1234')  GROUP BY ``album``.``prefix``, ``album``.``name``, ``album``.``album_artist``, ``album``.``release_type``, ``album``.``mbid``, ``album``.``year``  ORDER BY ``album``.``name``, ``album``.``disk``, ``album``.``year``
2020-01-16 21:36:40 [xyz] (dba.class) -> Error_query MSG: …

Fixed GROUP BY error in artist.class get_albums

---

lib/class/vainfo.class.php

Vorbis files currently do not load the rating from the metadata correctly. This is because `$parsed['rating']` is expected to be an dictionary of ratings (0-5) for each user ID, but the Vorbis comment code does not know how to handle this. It simply sets `$parsed['rating']` directly to the Vorbis "RATING" tag value, without creating a dictionary nor scaling.
This pull request fixes this so that if there is a Vorbis "RATING" tag, it will be interpreted as a percentage, scaled and used for the rating tag for the super user (ID -1). This is the similar behaviour to the IDv3 POPM rating when the user in the tag is unknown, where it also defaults to the super user (ID -1).
The exact format of the rating tag used here (i.e. a percentage from 0-100) is the same as described in …

Read vorbis rating tag

---

templates/show_arts.inc.php

The logic to display each image in the table cells was broken in the case some of the images where filtered out due to size constraints.
The new logic simply keeps a counter for the table cell that gets increased only when an image is added to a cell. After 4 cells are filled a new row is created.

Fix the layout when displaying images in "Find art" and some are filtered out.

---

config/ampache.cfg.php.dist
lib/class/channel.class.php
lib/class/live_stream.class.php
lib/class/media.interface.php
lib/class/podcast_episode.class.php
lib/class/preference.class.php
lib/class/song.class.php
lib/class/song_preview.class.php
lib/class/stats.class.php
lib/class/subsonic_api.class.php
lib/class/update.class.php
lib/class/useractivity.class.php
lib/class/video.class.php
lib/login.php
lib/preferences.php
templates/show_song.inc.php
templates/show_song_row.inc.php
templates/show_songs.inc.php

As explained in #2288, this adds the capability for ampache to recognize whether a song is skipped. 
Therefore, there is an adjustable skipping threshold (how much time played counts as not skipped), a skipping counter in the GUI and of course the database infrastructure and recognition to recognize and save the skip count. 
Subsonic API is supported as well, however with a little change that will make a delayed entry of played or skipped impossible (DSub for example is working on an offline mode submitting changes later). On the good side however, it is working without turning on scrobbling in the client.

Add Skipping functionality

---

lib/class/xml_data.class.php

The third parameter for `array_splice` defaults to `null` if not provided. So this was an unnecessary check as both calls are identical.
`function array_splice (array &$input, $offset, $length = null, $replacement = null) {}`

Unnessary null check for XML tags function

---

modules/plugins/Gravatar/Gravatar.plugin.php

I discovered the issue with my own ampache installation. I had mixed-content warnings, while behind a reverse proxy with `force_ssl = true` in my ampache config file.
Note: I tested on my own install, it works as expected.

[Gravatar Plugin] Make sure https is used when force_ssl is configured

---

lib/class/subsonic_api.class.php

Change operator for query in getlyrics from 'not equal' to 'equal'.
This way an SQL query is built that fetches song lyrics with Artist and Title **equal** to the given parameters instead of songs with Artist and Title **not equal** to the given parameters (which returns always the same song).

Fix for issue #2374: Subsonic API returns lyrics of wrong song

---

lib/javascript/search.js

proposal for feature #2425 
sorting is done in javascript. Because the subtypes are stored as objects in `var types` via search-data.php, it's not possible to do the sorting on the server side.

case insensitive sort on metadata field list in advanced search

---

modules/localplay/upnp/UPnPDevice.php
modules/localplay/upnp/UPnPPlaylist.php
modules/localplay/upnp/upnpplayer.class.php

The UPnP localplay code expects to retrieve session information using named keys.
The Session::create and Session::exists functions now use 'stream',
which allows the $sid to be set.
Should address #2446.

Update session code to use 'stream' instead of 'api'

---

lib/i18n.php

When loading every single page the localized .po files are loaded. However I managed to improve the performance by loading the .mo files, which are machine readable and therefore optimized for machine parsing, rather than the .po files which are meant for human readability.
Using a Raspberry Pi 2 as an ampache server, the load times of simple pages were before in the order of ~0.9s (as reported in the page footer). After this change, load times have been reduced by ~0.4s on average, which is a big boost. The test has been done with es_ES, de_DE and ja_JP localizations, all showing similar performance improvements.

Improve performance by loading .mo gettext files rather than .po

---

templates/show_preference_box.inc.php

The preferences page shows a subcategory that until now has not been localized. The problem is the string was passed to ucwords _before_ being localized, and since that's the msgid, then it couldn't be found in the catalogue. Now ucwords is applied to the localized string instead.

Fix non-locallized subcategories in preferences

---

lib/preferences.php

The preference settings that the user doesn't have the permissions to change had a hardcoded string ("Disabled", "Enabled) so no translation is shown in the UI.
This PR fixes that, by adding the corresponding T_().
I have executed gather-messages.sh -g to generate a new messages.pot which I have included in the PR. However it is not clear to me whether the .po and .mo files need to be regenerated (with gather-messages.sh -ma I guess) or whether this is done automatically by transifex once a new messages.pot is there. If the former, I can easily run the command and remove the obsolete strings (there are two unrelated obsolete strings) to this PR.

Added translation of settings that cannot be changed by user

---

lib/class/art.class.php
templates/show_get_art.inc.php

Also use the new ART_SEARCH_LIMIT constant in the template to define the
default.
References: d3e4aaeeab87ba697063f36d70d27cf5da915d05

Repair global constant call

---

lib/class/subsonic_api.class.php
lib/class/subsonic_xml_data.class.php

returning getArtistInfo2 and getSimilarSongs2 into respectivly 'artistInfo2' and 'similarSongs2' childs.
previously returning into 'artistInfo' et 'similarSongs' childs.

[subsonic API] artistInfo2 & similarSongs2 correct return childs

---

artists.php
tvshows.php

It looks like that functionality is unused.
Also, some of the used methods in here (`show_alphabet_list`, `show_alphabet_form`, ...) do not longer exist, so it's at least broken.
Or - if there's some magic behind this - someone could enlighten me :bulb:

Drop non-working `match` functionality

---

lib/class/mailer.class.php

the "true"/"false" values in ini file is parsed as 1/0 and thus strict equality check won't work

mailauth is an integer and not boolean

---

lib/javascript/jplayer.ext.js
templates/show_html5_player_headers.inc.php

A long time annoying issue removed. I love to use the well known shortcut `CTRL+f` to find something on the page but jPlayer bind the `f` key without checking if `CTRL` was pressed too. With the useless fullscreen view, we don't need to bother anymore.
Have a nice day.

jPlayer fullscreen shortcut disabled

---

docs/CHANGELOG.md
lib/class/browse.class.php
templates/show_playlist.inc.php
templates/show_playlist_medias.inc.php
templates/show_playlist_row.inc.php
templates/show_playlists.inc.php
templates/show_search.inc.php
themes/reborn/templates/dark.css
themes/reborn/templates/default.css
themes/reborn/templates/light.css

Initially, it was added as a column in `show_playlists.inc.php`, however, after user feedback, it has been changed to be shown inside `show_playlist_medias.inc.php` for a better look.
note 1: It works both for normal playlists and smart playlists.
note 2: In case the duration is >86400 seconds (a day) the hour format takes in all the extra hours i.e. 99728s = 27:42:08.

#2527 Playlist duration added to UI

---

lib/class/ApiMethods/GetIndexesMethod.php
lib/class/xml_data.class.php

Hi,
I would like to support Radio Stations in my client. This pull request adds them to the get_indexes API method. Please consider for inclusion in the next version.
Thank you

Add live streams to getindexes API method

---

lib/class/subsonic_api.class.php

The hls view logic didn't used to handle videos, and also used a `Content-Type` header that didn't work for vlc. This fixes both those issues.
You can read more about the header stuff here: https://tools.ietf.org/html/rfc8216#section-4

Make hls view work for video/vlc

---

lib/class/vainfo.class.php

Currently, metadata plugin doesn't work in `develop`.
This probably broke [here](https://github.com/ampache/ampache/commit/1919bbf0b5ce5a73350379724096d5ce48645896#diff-f2e481950543ffffda33cd96e45effdcf291fbde50e3c2000c60f9a79c6a63daR640).
`$tag_order` is always an array.
I think this wrapping is unnecessarily.

Fix metadata plugin

---

config/ampache.cfg.php.dist

`[...]` is a character class.  Repeating `|` is not needed.

Fix default value of additional_genre_delimiters

---

lib/class/vainfo.class.php

When updating the catalog, it was not able to determine the file type of opus files:
```
2021-01-09T21:23:47+00:00 [admin] (vainfo.class) -> Unable to determine file type from opus on file /data/musik/Porcupine Tree/2008 - We Lost the Skyline/01. The Sky Moves Sideways.opus
2021-01-09T21:23:47+00:00 [admin] (vainfo.class) -> Checking /(.+?)\/([0-9]+?)\s\-\s(.+?)\/([0-9]+?)\.\s(.+?)\..+$/ _ Array on Porcupine Tree/2008 - We Lost the Skyline/01. The Sky Moves Sideways.opus
2021-01-09T21:23:47+00:00 [admin] (vainfo.class) -> /(.+?)\/([0-9]+?)\s\-\s(.+?)\/([0-9]+?)\.\s(.+?)\..+$/ matched Porcupine Tree/2008 - We Lost the Skyline/01. The Sky Moves Sideways.opus on Porcupine Tree/2008 - We Lost the Skyline/01. The Sky Moves Sideways.opus
2021-01-09T21:23:47+00:00 [admin] (vainfo.class) -> …
```

recognize opus in _clean_type

---

public/themes/reborn/templates/dark.css
public/themes/reborn/templates/default.css
public/themes/reborn/templates/light.css

This addresses several issues
1. Major layout shift when hovering over last item of first row in mashup view (sporadic)
2. Border appears when hovering over .item_art but no action is available; another border appears when the img is hovered which also has minor layout shift
Now a single outline appears when hovering over the art as expected
3. Cover art box-shadow was being clipped

Use outline for album art hover

---

modules/localplay/upnp/upnpplayer.class.php

Introduced by ffacc2285f3450c6725d547a1226927874db6a49, backported from
source-changes

Add missing parameter for Upnp_Api::createDIDL call

---

public/templates/show_album.inc.php
public/templates/show_album_group_disks.inc.php
public/templates/show_artist.inc.php
public/templates/show_democratic.inc.php
public/templates/show_ip_history.inc.php
public/templates/show_label.inc.php
public/templates/show_labels.inc.php
public/templates/show_live_streams.inc.php
public/templates/show_playlist.inc.php
public/templates/show_podcast.inc.php
public/templates/show_podcasts.inc.php
public/templates/show_pvmsg.inc.php
public/templates/show_search.inc.php
public/templates/show_search_options.inc.php
public/templates/show_searches.inc.php
public/templates/show_tvshow.inc.php
public/templates/show_tvshow_season.inc.php
public/themes/reborn/templates/default.css
src/Module/Api/Ajax.php

I noticed quite a few action items had separate links for the img and text, or links were missing from either one.
Now all actions (#information_actions) have both img and text inside a single ```<a>```

Added Ajax::button_with_text to have img and text in single link

---

resources/templates/playlist/new_dialog.xhtml
src/Gui/GuiFactory.php
src/Gui/GuiFactoryInterface.php
src/Gui/Playlist/NewPlaylistDialogAdapter.php
src/Gui/Playlist/NewPlaylistDialogAdapterInterface.php
src/Module/Api/Edit/ShowEditPlaylistAction.php
tests/Gui/GuiFactoryTest.php
tests/Gui/Playlist/NewPlaylistDialogAdapterTest.php

This is a serious flaw. The playlist-edit actions allows the object-id
to be int[] instead of int - but the app performs an int-cast on the
list to use it for some checks beforehand.

Allow the object id to be used as a list of ids

---

src/Repository/Model/Metadata/Metadata.php
src/Repository/Model/Metadata/Model/Metadata.php

Fixes issue #2830
Also a correction to write only the classname (e.g. 'Song') into table field `metadata.type`, and not the classname with the full namespace.
This also solves a infinite loop when updating the catalog with custom metadata enabled

Give correct MetadataField in Ampache\Repository\Model\Metadata\Model\Metadata

---

src/Module/Util/VaInfo.php

Don't overwrite null values with an empty string if custom metadata is enabled.  This fixes a problem with replaygain and r128 gain metadata.
Also removed a redundant check `is_array($value)` in ternary.

don't overwrite null value with empty string in metadata

---

docs/CHANGELOG.md
src/Plugin/AmpacheGravatar.php

As the browser vendors tend to drop http in near future (or at least add
warnings, etc...) and _every_ client out there is capable of modern TLS
versions, it's time to enforce https - at least when building the
gravatar-urls.
Related #2366
Fixes #1797

Make gravatar urls https-only

---

src/Module/Util/VaInfo.php

another fix to tag sources case, causing plugin metadata not in results
convert all tagsources to lowercase, also occurrences of 'getID3'
only loop over plugins in _get_plugin_tags
return artists as array, don't prepare metadata outside VaInfo
HINT: replaygain metadata partly broken

fix plugin metadata not in results

---

src/Config/ConfigurationKeyEnum.php
src/Module/Art/Collector/LastFmCollectorModule.php
src/Module/Song/Tag/SongId3TagWriter.php
src/Module/Util/VaInfo.php
src/Module/Util/VaInfoInterface.php
src/Repository/Model/Art.php
src/Repository/Model/Artist.php
src/Repository/Model/Catalog.php

1. Added check for existance of metaflac and vorbiscomments before writing flac or oga tags.
2. getID3 library doesn't remove pictures, only vorbiscomments.  Added work-around to replace existing file images in flac or oga files.
3.  Added missing constant `WRITE_ID3_ART` to `src/Config/ConfigurationKeyEnum.php`
This PR hasn't been tested on Windows: Specifically the Windows code in Vainfo.php.  **Hopefully someone can test PR in Windows environment before merging**.

Fix /improved tag write

---

public/templates/header.inc.php

- Fixes ```Uncaught TypeError: n is undefined``` when result rows are hovered on, due to the autocomplete widget expecting .data()
- Fixes #371, pressing [Enter] now navigates to the selected item
- Clicking into search field with existing value will reopen results (having to add/remove characters just to trigger previous results is annoying)
- Preserve the search string instead of replacing it with the selected item
- Fixes the [Tab] key bind

Search bar improvements

---

src/Module/Util/VaInfo.php

It seems that the replaygain tags put in OGG files by foobar2000 for example are processed by getId3 but not by vainfo.php. As a result, no replay gain is seen during playback of OGG files. This patch should process these tags from OGG files:
- replaygain_track_gain
- replaygain_track_peak
- replaygain_album_gain
- replaygain_album_peak

replaygain not read in ogg files.

---

public/templates/header.inc.php
public/templates/show_html5_player.inc.php
public/templates/show_html5_player_headers.inc.php
public/templates/sidebar.inc.php
src/Module/Application/Logout/LogoutAction.php
src/Module/System/InstallationHelper.php
src/Module/System/Session.php
src/Module/Util/Captcha/easy_captcha_persistent_grant.php
src/Repository/Model/Browse.php

Fixes #2910
- Use the PHP7.3 array parameter for setting cookies, which lets you specify a ```samesite``` value.
- Amends the JS cookies which were using an old workaround to set samesite.
One problem remains though, I haven't been able to get the ```ampache``` (session_name) cookie to accept a samesite value, and I don't fully understand why that is as according to the PHP docs it should happily accept the samesite value. 
Assuming its to do with it being a session cookie (session-set-cookie-params), the furthest I could get was changing the PHP setting ```session.cookie_samesite = "Strict"```...

Specify SameSite on all cookies (use php 7.3 array parameter)

---

src/Repository/Model/Catalog.php

This fix following error while executing `bin/cli run:updateCatalog -a`
```
PDOException SQLSTATE[HY093]: Invalid parameter number: number of bound variables does not match number of tokens
(thrown in /srv/http/ampache/src/Module/System/Dba.php:85)
Stack Trace:
0) PDOStatement->execute()
at /srv/http/ampache/src/Module/System/Dba.php:85
1) Ampache\Module\System\Dba::_query()
at /srv/http/ampache/src/Module/System/Dba.php:61
2) Ampache\Module\System\Dba::query()
at /srv/http/ampache/src/Module/System/Dba.php:122
3) Ampache\Module\System\Dba::read()
at /srv/http/ampache/src/Repository/Model/Catalog.php:1108
4) Ampache\Repository\Model\Catalog->get_artist_ids()
at /srv/http/ampache/src/Module/Catalog/Update/UpdateCatalog.php:133
5) Ampache\Module\Catalog\Update\UpdateCatalog->update()
at …
```

Add catalog id parameter in sql for querying with count filter

---

public/templates/show_arts.inc.php
src/Repository/Model/Art.php

First change is to keep aspect ratio of original images during art selection
Second is to crop non-square images from the centre (or slightly above centre for portrait images making the assumption that faces would most likely be higher), instead of squashing the image into being a square. This does mean there is a possibility of faces being cut off but I feel that is better than distorted images

crop images from the centre instead of resizing into a square

---

.gitignore
public/templates/header.inc.php
public/templates/install_footer.inc.php
public/templates/show_debug.inc.php
public/templates/show_html5_player_headers.inc.php
public/templates/show_registration_confirmation.inc.php
public/templates/show_user_activate.inc.php
public/templates/show_user_registration.inc.php
public/templates/stylesheets.inc.php
public/themes/reborn/templates/dark.css
public/themes/reborn/templates/default.css
public/themes/reborn/templates/light.css
src/Module/Application/Admin/System/ClearCacheAction.php
src/Module/System/AutoUpdate.php
src/Module/Util/AssetCache.php

This uses the MD5 hash of a file to create a unique cached version, to avoid 'just clear your browser cache' issues
- Reference a cached version of asset if it exists, otherwise create cached version and reference it, or fallback to original file
- Added 'Clear Assets Cache' option to Ampache Debug page
- Change paths in CSS to be web root relative to account for different physical locations of original and cached CSS file
Not sure if I should also clear the asset cache during clean_catalog() just so its periodically cleared?

Cache bust some frequently updated assets

---

src/Module/Api/Method/PodcastEpisodeDeleteMethod.php

Regardless of the access rights, the user was not able to delete a podcast_episode via the Ampache API method 'PodcastEpisodeDelete' (error: 'Require: 75'). I tested it with admin rights. Via the subsonic API the action performed without errors.
With this pull request the Ampache API method 'PodcastEpisodeDelete' behaves as the subsonic counterpart 'deletePodcastEpisode':
https://github.com/ampache/ampache/blob/a93fe6a4bff4b003c98f3da7016183d03dc7e57c/src/Module/Api/Subsonic_Api.php#L2361
The same check is performed here in the Ampache API method 'PodcastDelete': https://github.com/ampache/ampache/blob/a93fe6a4bff4b003c98f3da7016183d03dc7e57c/src/Module/Api/Method/PodcastDeleteMethod.php#L61

fix user access for API method PodcastEpisodeDelete

---

public/templates/show_album.inc.php

replaced user_dn with username as property to check for group membership in ldap.

fix for ldap_require_group does not work #2388

---

src/Module/Util/AmpacheRss.php

This PR will improve the description of the rss feeds that ampache creates. The new content looks like this:
```
User: my_user
Title: The Song title
Artist: My Artist
Album: The Album Titile
Play date: 21/1/22 19:29
```
Apart from improving a bit the contents so that it is more useful there is an additional benefit: in some RSS readers (like Akregator), if the description of the feed does not change with respect to the stored feed items then it is considered as the same feed item. If a song is played twice within the 10 last feed items then it appears as only one played item. With this change it will appear as two distinct items with a different play timestamp.

Improve description of rss feed

---

src/Module/Api/Subsonic_Xml_Data.php

This PR will avoid sending the cover art for albums that do not have art. This prevents errors when the client will ask for a non-existing art.
It would fix #3149.

subsonic: Do not send convertArt for album if art does not exist

---

src/Module/Catalog/Catalog_Seafile.php

Error Typed property Ampache\Module\Catalog\Catalog_Seafile::$count must not be accessed before initialization
(thrown in src/Module/Catalog/Catalog_Seafile.php:340)
Stack Trace:
0) Ampache\Module\Catalog\Catalog_Seafile->insert_song()
at src/Module/Catalog/Catalog_Seafile.php:285
1) Ampache\Module\Catalog\Catalog_Seafile->Ampache\Module\Catalog\{closure}()
at src/Module/Catalog/SeafileAdapter.php:268
2) Ampache\Module\Catalog\SeafileAdapter->for_all_files()
at src/Module/Catalog/SeafileAdapter.php:266
3) Ampache\Module\Catalog\SeafileAdapter->for_all_files()
at src/Module/Catalog/Catalog_Seafile.php:297
4) Ampache\Module\Catalog\Catalog_Seafile->add_to_catalog()
at src/Module/Catalog/Update/UpdateCatalog.php:111
5) Ampache\Module\Catalog\Update\UpdateCatalog->update()
at …

fix uninitialized var access

---

src/Module/Cli/UpdateCatalogCommand.php

This is a minor improvement after #3041 to add the default actions in the help of cli run:updateCatalog --help

Update help with the default actions

---

src/Module/Art/Collector/LastFmCollectorModule.php

Fixes #2268 
Example is the last row
**Before**
**After**

Remove duplicates and order largest to smallest for LastFM art collector

---

src/Module/Playback/Stream_Playlist.php

This patch create a big sql query instead that a long list of  single queries.  The method is way faster.
The only downside that i think is that, in case of huge playlists ( like 10000 or more ) the server could not hanlde it. But i think that huge playlists are already a problem.
It partially solves #2626 , does not handle the first part of the problem, the url creation, but the speed up big ( like 80% less time )

sql bulk query to speed up playlist streaming

---

src/Module/Playback/Stream_Playlist.php

This patch divides the sql query in chunks of length 500, the impact on the performance is negiglible ( for 10000 items are 20 queries instead 10000, for 100000 are 200 and so on... and the bottleneck for those numbers is the server ), but avoid to  risk to overload the server. Btw, with list bigger than 2-3000 items the browser start to show some problem ( firefox start complaining that the page is too slow and it is better to block )

Division of sql bulk query in  chunks

---

src/Repository/Model/Catalog.php

Testing album_map update, the code removed the artist entry without checking if the song is the last of an artist ( not album_artist ) in an album. This patch solve this issue.

Remove the entry on album_map only if it is the last song of an album

---

src/Module/Playback/Localplay/Xbmc/AmpacheXbmc.php

The correct name of the field is pass, not password

Fix db query error in xbmc localplay

---

src/Module/Playback/Localplay/Xbmc/AmpacheXbmc.php

Not perfect patch, but a working one.
Fixes autoplay when playlist is new.
Do not autoplay when another song is playing ( changing playlist ) , cause both have the same id.
It should be better to place getActivePlayers in the status, but i have no idea ho to do it.

Fix autoplay in xbmc localplay

---

src/Repository/ArtistRepository.php

The sql result gives an array where artist_id is the name of the field , but the function checks id as name. This broke random artists function.

Correct sql result field in getRandom artist

---

src/Repository/Model/Podcast.php

Handle a time starting 3:23:01, too, actual regex catches only hours starting with 0.
Fixes #3284

Fix pocast episode time regex

---

src/Module/Application/Login/DefaultAction.php

Add the default filter group ID to the create user call.  Use a variable name instead of a constant.
Closes #3308

Add the default filter group to the create user call.

---

src/Repository/Model/Album.php

Hi there,
Thanks a lot for this amazing software I'm using for such a long time!
The initial issue was that new album didn't get the time column filled in.
I fixed the album time value not updated when the initial value is `NULL`. The initial value should be `0` instead of `NULL` if we expect an integer, don't your think?
Have a nice day!

Fix album time update when time is NULL

---

src/Module/System/Core.php

Addresses issue #3343 which appears to have been caused by a typo in a function name,

Correct function call in proxy check

---

src/Module/Application/Image/ShowAction.php

Hi,
I found several issues in the actual implementation of the ETag header to enable 304 responses.
- Based on file https://github.com/ampache/ampache/blob/2ca159ba032fd1921438b27a4eb4b280f4719d0c/src/Module/Application/Image/ShowAction.php : ETag is compared at line L195 but is modified at line L230 (yes there is an explode at line L192 but, still, it isn't the same image).
- ETag should be betwen `"`
- 304 responses must have ETag header, or the next answer won't be cached.
- Expires headers is recommended with ETag

Fix 304 for images

---

src/Module/Api/Subsonic_Api.php

This allows clients such as Symfonium to sync properly.
Preserve the existing equals logic primarily because I am not familiar with common client patterns.
fixes #3420

Subsonic_Api: Allow empty queries

---

src/Module/Catalog/Catalog_local.php

This is preventing legitimate directories and files from being scanned into the catalog. ("Legitimate" here meaning files and directories where the name matches that of the album or track, such as "...Like Clockwork".
This style of skipping the pseudo-directories is consistent with that of src/Repository/Model/Art.php.
fixes #3422

Catalog: Stop filtering items beginning with a "."

---

src/Module/Cli/ExportPlaylistCommand.php
src/Module/Playlist/PlaylistExporter.php
src/Module/Playlist/PlaylistExporterInterface.php

`./bin/cli export:playlist /tmp/ezstream-tempo/ m3u playlists` export **all** playlist. Can be quite long.
This patch add an optional parameters to allow export of just one playlist. Example: 
`./bin/cli export:playlist /tmp/ezstream-tempo/ m3u playlists 42`

Add possibility to export just one playlist

---

public/templates/show_label.inc.php

The searches for labels contain a wrong URL, basically an extra "s". This fixes that and aligns the ddgo URl with other searches.

Fix Duckduckgo searches for labels

---

src/Module/Util/AmpacheRss.php

This small PR simply avoids scrubing the Ampache installation title when using the RSS output. If the title contains accents some RSS readers have trouble. For instance, Firefox is unable to parse the XML, whereas Akregator will ignore the character with the accent.
Since for the RSS XML there is no need to escape HTML characters, simply removing scrub_out() call will work
For a reference, this is the error shown in Firefox when it fails to parse the XML without this patch:

Do not scrub title for RSS output

---

public/daap/.htaccess
public/play/.htaccess.dist
public/rest/.htaccess.dist

Since Apache r1908095 [1], it has become far less forgiving of 'invalid characters' in Rewrite patterns, for example patterns with spaces.
Songs often have spaces in the filenames, so it is necessary to pass them.
[1] https://svn.apache.org/viewvc?view=revision&revision=1908095
[2] https://webmasters.stackexchange.com/questions/141837/ah10411-rewritten-query-string-contains-control-characters-or-spaces
Please note, I'm not really an expert with the Apache incantations, so I've indiscriminately added the B and BNP flags to every RewriteRule.  I think that's necessary and it works, but it might need a basic sanity check.

Fix htaccess parameters to pass valid characters

---

config/ampache.cfg.php.dist
public/templates/show_login_form.inc.php

"login_message" is mentioned on the login page but isn't present in the config, this fixes that

Set login_message from config

---

src/Module/Api/Method/Api4/Download4Method.php
src/Module/Api/Method/Api4/Stream4Method.php
src/Module/Api/Method/Api5/Download5Method.php
src/Module/Api/Method/Api5/Stream5Method.php
src/Module/Api/Method/DownloadMethod.php
src/Module/Api/Method/StreamMethod.php

download/stream API methods were fine on my local dev setup, but on my remote server (ampache-docker which comes with curl installed) they were returning ```http://localhost/play/index.php?ssid...``` due to ```function_exists('curl_version'),``` being ```true```
The default for ```play_url()``` is ```local: false``` so after removing the checks the correct URLs were returned
After this change the only other instances of ```local``` being checked or forced are these places:
https://github.com/ampache/ampache/blob/e9408ed52c214680b650a803f653c29dfb86a753/src/Module/Api/Daap_Api.php#L437
https://github.com/ampache/ampache/blob/e9408ed52c214680b650a803f653c29dfb86a753/src/Module/Api/Subsonic_Api.php#L1396
https://github.com/ampache/ampache/blob/e9408ed52c214680b650a803f653c29dfb86a753/src/Modu …

Server would return incorrect url if 'local' was true

---

src/Repository/Model/Art.php

Prepend the art title for MP3 tags with `ID3 ` as it was missing and then failing to fetch the embedded art from said files.
Also made a minor refactor to simplify the code.

Fix for #3537: Prepend 'ID3 ' to the art title for MP3 tags

---

src/Repository/Model/Catalog.php

* During Catalog Check, bit rate mode for ogg ABR file must not be updated to VBR
Closes #3582

Avoid OGG ABR bitrate mode to be updated to VBR

---

src/Repository/Model/Catalog.php

* Complete test to use existing albumartist when no tag is available
Closes #3534

Avoid Orphan album artist when song has empty albumartist tag (#3534)

---

composer.json
docs/examples/AmpacheExample.php
phpunit.xml.dist
tests/Config/ConfigContainerTest.php
tests/Gui/Stats/CatalogStatsTest.php
tests/Module/Application/Admin/Access/Lib/AccessListItemTest.php
tests/Module/WebDav/WebDavFactoryTest.php

- Update data-provider method definitions (must be static now)
- Use PHP8 Attributes instead of annotations to call data-providers in tests
- Remove cache-warmup in `composer coverage` as it's no longer necessary

Upgrade phpunit to version 10

---

src/Module/Application/Admin/User/ShowDeleteApikeyAction.php
src/Module/Application/Admin/User/ShowDeleteAvatarAction.php
src/Module/Application/Admin/User/ShowDeleteRsstokenAction.php
src/Module/Application/Admin/User/ShowDeleteStreamtokenAction.php
src/Module/Application/Admin/User/ShowGenerateApikeyAction.php
src/Module/Application/Admin/User/ShowGenerateRsstokenAction.php
src/Module/Application/Admin/User/ShowGenerateStreamtokenAction.php
src/Module/Application/Admin/User/UserAdminApplicationTrait.php
tests/Module/Application/Admin/User/ShowDeleteApikeyActionTest.php
tests/Module/Application/Admin/User/ShowDeleteRsstokenActionTest.php
tests/Module/Application/Admin/User/ShowDeleteStreamtokenActionTest.php
tests/Module/Application/Admin/User/ShowGenerateApikeyActionTest.php
tests/Module/Application/Admin/User/ShowGenerateRsstokenActionTest.php
tests/Module/Application/Admin/User/ShowGenerateStreamtokenActionTest.php
tests/Module/Application/Admin/User/UserAdminConfirmationTestTrait.php

Avoid c/p code by using a trait for all those user-admin confirmation dialogues. Also add some more tests.

Streamline and consolidate user-admin confirmations

---

src/Module/Application/Admin/User/ConfirmDeleteAction.php
src/Module/Application/Admin/User/ShowDeleteApikeyAction.php
src/Module/Application/Admin/User/ShowDeleteAvatarAction.php
src/Module/Application/Admin/User/ShowDeleteRsstokenAction.php
src/Module/Application/Admin/User/ShowDeleteStreamtokenAction.php
src/Module/Application/Admin/User/ShowGenerateApikeyAction.php
src/Module/Application/Admin/User/ShowGenerateRsstokenAction.php
src/Module/Application/Admin/User/ShowGenerateStreamtokenAction.php
src/Module/Application/Search/SearchAction.php
src/Module/System/Core.php
src/Module/Util/RequestParser.php
src/Module/Util/RequestParserInterface.php
src/Repository/Model/User.php
tests/Module/Application/Admin/User/ConfirmDeleteActionTest.php
tests/Module/Application/Admin/User/UserAdminAccessTestTrait.php

Also:
- Add a method in RequestParser to proxy the Core::form_verify-call (which helps in making this handler testable)
- Add a test-trait for repetetive tests within the user admin access context

Add tests for admin user deletion confirmation

---

src/Module/Application/Admin/User/ShowDeleteApikeyAction.php
src/Module/Application/Admin/User/ShowDeleteAvatarAction.php
src/Module/Application/Admin/User/ShowDeleteRsstokenAction.php
src/Module/Application/Admin/User/ShowDeleteStreamtokenAction.php
src/Module/Application/Admin/User/ShowGenerateApikeyAction.php
src/Module/Application/Admin/User/ShowGenerateRsstokenAction.php
src/Module/Application/Admin/User/ShowGenerateStreamtokenAction.php
src/Module/Application/Search/SearchAction.php
src/Module/System/Dba.php
src/Module/Util/Graph.php
src/Repository/Model/Catalog.php
src/Repository/Model/User.php
src/Repository/UserRepository.php
src/Repository/UserRepositoryInterface.php

The method returns statistical data related to users and sessions and is not directly related to a User instance.
Also add a dba-method to retrieve just the first column of a result.

Move User::count() into UserRepository

---

.github/workflows/phplint74.yml

This will lint all pushes and pull-requests to master and develop with php7.4. tests- and vendor-folder are excluded from linting

Add php74 lint github action

---

phpstan-baseline.neon
src/Module/Api/ApiHandler.php
src/Module/Api/Authentication/Gatekeeper.php
src/Module/Api/Method/Api4/UserCreate4Method.php
src/Module/Api/Method/Api5/UserCreate5Method.php
src/Module/Api/Method/LostPasswordMethod.php
src/Module/Api/Method/RegisterMethod.php
src/Module/Api/Method/UserCreateMethod.php
src/Module/Util/VaInfo.php
src/Repository/Model/User.php
src/Repository/UserRepository.php

Those static methods just proxy calls to the UserRepository. Those can now simply be replaced by calling the methods directly on the repo

Remove proxy methods from User

---

public/templates/show_playlist_media_row.inc.php
src/Application/Api/Ajax/Handler/PlaylistAjaxHandler.php

The action builds a new browse instance having a higher id than the original browse instance. This is the reason why the UI item cannot be updated with the content of the response.
Related to #3651

Submit the current browse-id when deleting items from playlists

---

composer.json
phpstan-baseline.neon
public/templates/show_add_shout.inc.php
public/templates/show_shoutbox.inc.php
src/Application/Api/Ajax/Handler/SongAjaxHandler.php
src/Config/service_definition.php
src/Module/Application/Shout/ShowAddShoutAction.php
src/Module/Database/DatabaseConnectionInterface.php
src/Module/Database/DbaDatabaseConnection.php
src/Module/Database/Exception/DatabaseException.php
src/Module/Database/Exception/QueryFailedException.php
src/Module/System/Dba.php
src/Repository/ShoutRepository.php
tests/Repository/ShoutRepositoryTest.php

Static methods are hard to test/not testable, therfor we need a solution for quering the database using non-static methods.
The DatabaseConnection-class will provide non-static methods - currently only `query` is available. More methods will follow on a on-demand basis.
Use the new DatabaseConnection within the ShoutRepository and add tests for all existing methods.

Provice a non-static database access

---

README.md

It pointed to the old `source-changes` branch, we need `develop` in here.

Correct coverage badge url in readme.md

---

phpstan-baseline.neon
src/Module/Application/Playback/Play2Action.php
src/Module/Application/Playback/PlayAction.php
src/Module/Beets/Catalog.php
src/Module/Catalog/Catalog_Seafile.php
src/Module/Catalog/Catalog_dropbox.php
src/Module/Catalog/Catalog_local.php
src/Module/Catalog/Catalog_remote.php
src/Module/Catalog/Catalog_subsonic.php
src/Repository/Model/Catalog.php

Properties like `file`, `size` or `f_file` got temporarily overwritten by some catalog types during playback preparations. This should not happen as those properties represent the internal state of the object and are not meant to be some sort of `data storage` to carry some temporary information from place a to b.
I tested this with certain configuration but this surely somewhat experimental...

Prevent the playback from temporarily updating media properties

---

composer.json
composer_old.json
src/Config/ConfigContainer.php
src/Config/ConfigContainerInterface.php
src/Config/ConfigurationKeyEnum.php
src/Module/Podcast/Feed/FeedLoader.php
src/Module/Podcast/PodcastEpisodeDownloader.php
src/Module/Podcast/PodcastEpisodeDownloaderInterface.php
src/Module/Util/UtilityFactory.php
src/Module/Util/WebFetcher/Exception/FetchFailedException.php
src/Module/Util/WebFetcher/WebFetcher.php
src/Module/Util/WebFetcher/WebFetcherInterface.php
src/Module/Util/service_definition.php
src/Repository/Model/Catalog.php
src/Repository/Model/Podcast_Episode.php
tests/Config/ConfigContainerTest.php
tests/Module/Podcast/PodcastEpisodeDownloaderTest.php
tests/Module/Util/UtilityFactoryTest.php
tests/Module/Util/WebFetcher/WebFetcherTest.php

- Use curl for both, loading the feed and downloading the episodes
- Respect proxy-settings when downloading episodes
Maybe we should consider adding "curl" as a required php-module (instead of optional) as certain locations rely on at least `curl_init` being available.

Rework podcast-feed and -episode loading

---

src/Module/Util/WebFetcher/WebFetcher.php
tests/Module/Util/WebFetcher/WebFetcherTest.php

This raises the default timeout (30s) up to 300s to mitigate some issues with really slow servers. Anyhow, one should consider adding a config value instead of using a static timeout.

Set the curl timeout in WebFetcher

---

docs/CHANGELOG.md
src/Plugin/AmpacheBitly.php

Fixes #2476 
Requires a [Bitly ](bitly.com)account
Generate a ```token``` at https://app.bitly.com/settings/api
Get your ```group_guid``` from ```https://app.bitly.com/{GROUP_GUID}``` or Account Settings > Groups (the GUID is in the URL, not the group name)
FYI Bitly (now?) only shortens 12 free links a month

Update to Bitly API v4

---

resources/sql/ampache.sql
src/Module/System/Update.php

Another low hanging fruit, fixes #2588 
Wayback Machine confirms its the same license https://web.archive.org/web/20070124060916/http://www.fmpl.org/fmpl.html
That guy (Ram) is the current maintainer, says so at the very bottom: http://www.ram.org/ramblings/philosophy/fmp/fmpl/fmpl.html

Update link for FMPL license

---

public/templates/show_html5_player.inc.php

MediaSession API allows to advertise currently playing track and allows some control from the OS via the browser. (e.g. MPRIS & playerctl on Linux.)
This commit implements the following:
- expose song info (track name, artist name, artwork) via the MediaSession API.
- allow next song/previous song control via the MediaSession API.
I tested with firefox 121 & google-chrome 120 on Fedora 39.
All comments are welcome !
Fixes #3438

Web player: advertise song info via MediaSession API / MPRIS

---

src/Module/Statistics/Stats.php

Error in ampache log was:
[Runtime Error] Undefined array key "total_count" in file src/Module/Statistics/Stats.php(340)

Fix when some SQL query for stats have no match

---

phpstan-baseline.neon
src/Module/Api/Subsonic_Api.php
src/Module/Application/Installation/DefaultAction.php
src/Module/Application/Playback/Play2Action.php
src/Module/Application/Playback/PlayAction.php
src/Module/Art/Collector/SpotifyCollectorModule.php
src/Module/System/Update/Migration/V5/Migration500013.php
src/Module/Util/Captcha/easy_captcha.php
src/Module/Util/Captcha/easy_captcha_graphic_image_waved.php
src/Repository/Model/Album.php
src/Repository/Model/Metadata/Model/Metadata.php
src/Repository/Repository.php

Also removed the type-definition in easy_captcha.php as the resulting errors differs depending on the used php version. The type will be re-added after ugrading to php8+
#3765

Correct some type issues

---

src/Module/Api/Subsonic_Xml_Data.php

This is a fix/optimization for the retrieval of the cover arts of songs when using the subsonic API.
The current behaviour is "correct" in the sense that the corresponding cover is retrieved for a given song. However the cover_id for all the songs of the same album is different and is actually the song_id. This is allowed by the Ssubsonic API (http://www.subsonic.org/pages/api.jsp#getCoverArt), in the sense that one can give either a song_id or an album_id. However this can confuse clients that think that each of the songs has a different cover. I have tested strawberry music player and it tries to retrieve as many covers as songs, which makes the synchronization and order of magnitude slower than what it should if it only retrieves one cover per album. It also uses more space on the …

subsonic: do not send a different cover id for each song of the same album

---

public/podcast.php
public/templates/show_import_podcasts.inc.php
public/templates/show_podcasts.inc.php
src/Module/Application/Podcast/ImportPodcastsAction.php
src/Module/Application/Podcast/ShowImportPodcastsAction.php
src/Module/Podcast/Exchange/PodcastOpmlImporter.php
src/Module/Podcast/Exchange/PodcastOpmlImporterInterface.php
src/Module/Podcast/Exchange/PodcastOpmlLoader.php
src/Module/Podcast/Exchange/PodcastOpmlLoaderInterface.php
src/Module/Podcast/service_definition.php
tests/Module/Application/Podcast/ImportPodcastsActionTest.php
tests/Module/Application/Podcast/ShowImportPodcastsActionTest.php
tests/Module/Podcast/Exchange/PodcastOpmlImporterTest.php
tests/Module/Podcast/Exchange/PodcastOpmlLoaderTest.php

This allows the import of exported podcasts (e.g. from external app or other ampache instances) using the opml format.

Add opml import for podcasts #3737

---

.scrutinizer.yml

Has been removed due to unknown errors with bc7313fb000c59e0d26cdce8c9997cf67db5c484. Let's try to bring it back for good

Try to bring back the scrutinizer code coverage

---

src/Module/Util/Recommendation.php

This will lead to an error because some properties are not initialized properly if the artist is new (see #3765)

Dont try to search for recommendations for invalid artists

---

phpstan-baseline.neon
public/templates/show_license_row.inc.php
public/templates/show_manage_license.inc.php
src/Gui/Song/SongViewAdapter.php
src/Module/Api/Json4_Data.php
src/Module/Api/Json5_Data.php
src/Module/Api/Json_Data.php
src/Module/Api/Method/Api5/License5Method.php
src/Module/Api/Method/LicenseMethod.php
src/Module/Api/Xml4_Data.php
src/Module/Api/Xml5_Data.php
src/Module/Api/Xml_Data.php
src/Module/Application/Admin/License/DeleteAction.php
src/Module/Application/Admin/License/EditAction.php
src/Module/Application/Admin/License/ShowEditAction.php
src/Module/Util/ObjectTypeToClassNameMapper.php
src/Repository/LicenseRepository.php
src/Repository/LicenseRepositoryInterface.php
src/Repository/Model/License.php
src/Repository/Model/ModelFactory.php
src/Repository/Model/ModelFactoryInterface.php
src/Repository/Model/Song.php
tests/Gui/Song/SongViewAdapterTest.php
tests/Module/Application/Admin/License/DeleteActionTest.php
tests/Module/Application/Admin/License/EditActionTest.php
tests/Module/Application/Admin/License/ShowEditActionTest.php

- Use LicenseRepository::findById instead of direct class instantiation or the ModelFactory
- Replace License property-access by dedicated methods

Replace License loading by repo-method

---

docs/API-JSON-methods.md
docs/API-XML-methods.md
phpstan-baseline.neon
src/Module/Api/Method/UserMethod.php

If a user uses the Api via Api-Key, the user name of the user is not known. Api methods that require the specification of a user name cannot be used in this way.
This change allows the `username` parameter to be omitted and in this case returns all the information of the currently used API user - including the username.

Allow the user api method to return the current user info

---

phpstan-baseline.neon
public/templates/show_edit_license.inc.php
src/Module/Application/Admin/License/EditAction.php
src/Module/Application/Admin/License/ShowCreateAction.php
src/Module/Application/Admin/License/ShowEditAction.php
src/Repository/BaseRepository.php
src/Repository/BaseRepositoryInterface.php
src/Repository/LicenseRepository.php
src/Repository/Model/BaseModel.php
src/Repository/Model/Catalog.php
src/Repository/Model/License.php
src/Repository/Model/ModelInterface.php
src/Repository/Model/Shoutbox.php
src/Repository/ShoutRepository.php
src/Repository/ShoutRepositoryInterface.php
tests/Module/Application/Admin/License/EditActionTest.php
tests/Module/Application/Admin/License/ShowCreateActionTest.php
tests/Module/Application/Admin/License/ShowEditActionTest.php
tests/Repository/LicenseRepositoryTest.php
tests/Repository/Model/LicenseTest.php
tests/Repository/RepositoryTestTrait.php
tests/Repository/ShoutRepositoryTest.php

The BaseRepository defines a set of standard-methods (like `delete`, `prototype`, `findById`, etc..) for all inherting repositories. Make use of the BaseRepo in License- and ShoutRepo

Start the implementation of a BaseRepository and a generic ModelInterface

---

src/Module/System/Dba.php

Sometimes there is an error about bad syntax of the SQL query, but it's because the query is empty (sometimes it's just space).
Add specific error in the log about that. Will allow further debug later.

Add specific error if the SQL query is empty

---

src/Module/Util/Ui.php

Since commit 0d1ece0866, the default favicon is never shown.
Since the default value of the `custom_favicon` is an empty string and the use of the the default value `false`, the result of `AmpConfig::get('custom_favicon', false)` will never be unset.
Using the `??` operator always returns the `custom_favicon` setting, even if its NULL or an empty string. This causes the default favicon to never being shown even in the absence of the `custon_favicon` setting.
This issue has been introduced in commit 0d1ece0866.
Change `??` to `?:` to use the value of the `custom_favicon` setting only if it a non-empty string (`false`, `NULL` and `""` would evaluate to false in the test).

Really show default favicon by default

---

src/Repository/Model/Artist.php

This PR is a potential solution for #3833 . It basically sets the name that musicbrainz provides when creating a new album artist.
I don't find this solution particularly elegant for a couple of things:
1. It duplicates code that is found in function` check_mbid()`.
2. It assumes that the musicbrainz plugin is enabled. However this is already the case for `check_mbid()` function, so maybe it is the time to promote the plugin to be part of the core, since ampache already relies on musicbrainz metadata extensively for its correct behaviour.
Maybe this can be merged for the time being to fix the bug, but in the long run it is probably better to refactor the logic when creating a new artist to avoid a cleaner code.
BTW, other possibility to solve #3833 is to "properly" parse the `ALBUMARTIST` …

Use the name provided by musicbrainz rather than the ALBUMARTIST tag

---

src/Module/Util/Rss/AmpacheRss.php

This PR fixes the creation date of the RSS feed for the last played songs. Without that, the logs of ampache show the following error:
```
2024-03-04T17:35:48+00:00 [ampache] (log.lib) -> [Runtime Error] Trying to access array offset on value of type null in file src/Module/Util/Rss/AmpacheRss.php(491)
```
On top of that, the RSS publication date is set it unix time 0 (Thu Jan 01 00:00:00 1970 UTC).
After the fix, the publication date is correct:
```
...
<pubDate>Wed, 06 Mar 2024 19:38:05 +0000</pubDate>
...
```
Also, I refactored a bit the function that publishes the last played songs and improved the performance. At least in my ampache server,  retrieving the RSS feed before took ~2.5 s round trip, and after this PR it takes ~0.55 s. In the case of asking without an rsstoken, which …

Fix the publication date of RSS feeds.

---

phpstan-baseline.neon
src/Module/Util/Captcha/easy_captcha_graphic_image_waved.php

Captcha generation generate lot a noise because of implicit conversion. I don't like noise, it's noisy.
```
[Error] Implicit conversion from float 6.7 to int loses precision in file src/Module/Util/Captcha/easy_captcha_graphic_image_waved.php(122)
[Error] Implicit conversion from float 60.300000000000004 to int loses precision in file src/Module/Util/Captcha/easy_captcha_graphic_image_waved.php(122)
[Error] Implicit conversion from float 21.900000000000002 to int loses precision in file src/Module/Util/Captcha/easy_captcha_graphic_image_waved.php(123)
[Error] Implicit conversion from float 65.7 to int loses precision in file src/Module/Util/Captcha/easy_captcha_graphic_image_waved.php(123)
[Error] Implicit conversion from float 6.7 to int loses precision in file …
```

Fix implicit conversion

---

src/Repository/Model/Preference.php
src/Repository/Model/Song.php
src/Repository/Model/database_object.php

Can't display a song if it doesn't have any data in song_data table
Example : if 'select *  FROM `song_data` WHERE `song_id` = 57170;' is empty, the cache isn't populated.
It return false, and it must be an array
This patch allow false and array as return value.

Allow to display song even if no data in song_data table

---

public/lib/javascript/search.js
src/Module/Playlist/Search/AlbumDiskSearch.php
src/Module/Playlist/Search/AlbumSearch.php
src/Module/Playlist/Search/ArtistSearch.php
src/Module/Playlist/Search/LabelSearch.php
src/Module/Playlist/Search/PlaylistSearch.php
src/Module/Playlist/Search/PodcastEpisodeSearch.php
src/Module/Playlist/Search/PodcastSearch.php
src/Module/Playlist/Search/SongSearch.php
src/Module/Playlist/Search/TagSearch.php
src/Module/Playlist/Search/UserSearch.php
src/Module/Playlist/Search/VideoSearch.php
src/Repository/Model/Search.php

Perhaps counter-intuitively, we do want to scrub_out $rule[2], then convert any encoded chars back into 'normal' text after it has been sanitized

Decode scrubbed entities back into user-facing (but sanitized) text

---

public/templates/show_html5_player.inc.php

MPRIS: look like Android devices need more than one 96x96 thumbmail to display artwork

MPRIS: artwork working on Android devices

---

src/Repository/Model/Album.php

Hi there,
The artist name override the album name because of [the assign foreach here](https://github.com/Simounet/ampache/blob/73ce7cfe743e2a921e63fb954c3fd6fb56d39ab2/src/Repository/Model/Album.php#L439). This behavior doesn't seems to be very predictable to me.
I don't know when when the regression came in. I can search for it if you want me to.
Have a nice day.

Fix #3761 overrided album name

---

phpstan-baseline.neon
public/templates/show_manage_shoutbox.inc.php
src/Module/Api/Json4_Data.php
src/Module/Api/Json5_Data.php
src/Module/Api/Json_Data.php
src/Module/Api/Xml3_Data.php
src/Module/Api/Xml4_Data.php
src/Module/Api/Xml5_Data.php
src/Module/Api/Xml_Data.php
src/Module/Application/Admin/Shout/DeleteAction.php
src/Module/Application/Admin/Shout/EditShoutAction.php
src/Module/Application/Admin/Shout/ShowAction.php
src/Module/Application/Admin/Shout/ShowEditAction.php
src/Module/Application/Exception/ObjectNotFoundException.php
src/Module/Shout/ShoutCreator.php
src/Module/Shout/ShoutObjectLoader.php
src/Module/Shout/ShoutRenderer.php
src/Module/Util/Rss/Type/LatestShoutFeed.php
src/Repository/Model/Shoutbox.php
src/Repository/ShoutRepository.php
src/Repository/UserRepository.php
src/Repository/UserRepositoryInterface.php
tests/Module/Application/Admin/Shout/ShowEditActionTest.php
tests/Module/Shout/ShoutCreatorTest.php
tests/Repository/Model/ShoutboxTest.php
tests/Repository/ShoutRepositoryTest.php

Allows to retrieve the shout creator user instead of letting every location querying it directly

Add Shoutbox::getUser() method

---

public/templates/error_page.inc.php
public/templates/test_error_page.inc.php
src/Application/Api/Ajax/Handler/BrowseAjaxHandler.php
src/Application/Api/Ajax/Handler/CatalogAjaxHandler.php
src/Application/Api/Ajax/Handler/DefaultAjaxHandler.php
src/Application/Api/Ajax/Handler/DemocraticPlaybackAjaxHandler.php
src/Application/Api/Ajax/Handler/IndexAjaxHandler.php
src/Application/Api/Ajax/Handler/LocalPlayAjaxHandler.php
src/Application/Api/Ajax/Handler/PlayerAjaxHandler.php
src/Application/Api/Ajax/Handler/PlaylistAjaxHandler.php
src/Application/Api/Ajax/Handler/PodcastAjaxHandler.php
src/Application/Api/Ajax/Handler/RandomAjaxHandler.php
src/Application/Api/Ajax/Handler/SearchAjaxHandler.php
src/Application/Api/Ajax/Handler/SongAjaxHandler.php
src/Application/Api/Ajax/Handler/StreamAjaxHandler.php
src/Application/Api/Ajax/Handler/TagAjaxHandler.php
src/Application/Api/Ajax/Handler/UserAjaxHandler.php
src/Module/Api/Edit/AbstractEditAction.php
src/Module/Authentication/AuthenticationManager.php

Removes the superfluous use of the [evil bit](https://en.wikipedia.org/wiki/Evil_bit), keeping just one unobtrusive reference in the [header](https://github.com/ampache/ampache/blob/31088e92252c61eb4aaa8d8484c9c7fd86a2a870/public/templates/header.inc.php#L107). 
It was also being used for actual output so those have been renamed.
(sorry to whoever implemented this originally)

Lessen rfc 3514

---

phpstan-baseline.neon
public/templates/show_form_search.inc.php
src/Config/functions.php
src/Repository/Model/Preference.php

Instead of using `opendir()`/`readir()` I used `glob()`, so we get only directory with a `theme.cfg.php` file.
If themes dir have some trash in it (like `.htaccess` or anything else), it won't show.
I think I could even get rid of the `ksort()`, but I let it.

Rework of get_themes() to let PHP handle most of the work

---

src/Repository/Model/Art.php
src/Repository/Model/Artist.php
src/Repository/Model/Plugin.php
src/Repository/Model/Preference.php
src/Repository/UserRepository.php

Was just a quick fix, becoming a more general performance issue PR.
EDIT : went from 470 to 252 query in front page.
Plugin update
* Use more cache
Rework `Preference::get_by_user`
* Use cache
Art & Artist
* moar cache
Ampache 7 backward compatibility
* Replace check query for a quicker one:
```
MariaDB [ampache]> SELECT COUNT(`name`) from `user_preference`; 
+---------------+
| COUNT(`name`) |
+---------------+
|       1063622 |
+---------------+
1 row in set (0,180 sec)
MariaDB [ampache]> SELECT `name` from `user_preference` limit 1; 
+-----------+
| name      |
+-----------+
| ajax_load |
+-----------+
1 row in set (0,000 sec)
```

Address performance issues

---

public/templates/base.css
public/themes/reborn/templates/default.css
src/Application/Api/Ajax/Handler/SearchAjaxHandler.php
src/js/search.js

Hi there,
On the search bar, when you have more than one version of a same song (studio album, lives…) I thought it could be handy to display the album name.
I made a CSS adjustment to improve the styling on long line result.
I would also make a PR to reorder CSS loading. Seems weird to me that components CSS loads after ours.
Before:
```css
<link rel="stylesheet" href="https://ampache.simou.net/templates/base.css" type="text/css" media="screen">
<link rel="stylesheet" href="/templates/jquery-ui.custom.css" type="text/css" media="screen">
```
After:
```css
<link rel="stylesheet" href="/templates/jquery-ui.custom.css" type="text/css" media="screen">
<link rel="stylesheet" href="https://ampache.simou.net/templates/base.css" type="text/css" media="screen">
```
It would be easier to override …

Album name added to songs search

---

public/templates/show_recently_skipped.inc.php

This  removes the currently wrong RSS link to recently skipped that appears in a users profile.
This has actually been wrong since a while.  The RSS link to the recently skipped songs is actually pointing to the recently played songs.
I guess this is not a very useful feature, but can be restored (and properly implemented) if someone thinks it is useful.

Remove broken rss recently skipped

---

public/templates/show_html5_player.inc.php
public/templates/show_html5_player_headers.inc.php

This works as intended now, while a song is playing open a new tab and play a new song in that tab, the player in first tab will pause itself.

Fix pause across tabs

---

src/Module/Cli/UpdateCatalogCommand.php

It looks like now the default actions for run:updateCatalog cli command are -ceagt. But this has not been reflected in the documentation.
This PR fixes that.

Fix the run:updateCatalog default actions

---

src/Module/Util/VaInfo.php
src/Repository/Model/Catalog.php
src/Repository/Model/Video.php

After the upgrade to 7.4.2 I get the following exception when upgrading the catalog:
```
sudo -u www-data php -f /var/www/ampache/bin/cli run:updateCatalog -a
Leyendo Catálogo: "My Catalogue"
Empezar a añadir nuevos medios
Reading flac inside /music
TypeError Ampache\Repository\Model\Catalog::check_int(): Argument #2 ($max) must be of type int, float given, called in /var/www/ampache/src/Module/Util/VaInfo.php on line 660
(thrown in /var/www/ampache/src/Repository/Model/Catalog.php:3738)
```
It looks like after introducing type declarations the inputs of check_int in Catalog.php need to be integers. There are a few calls to that function that use 4294967294 as a hard-coded upper limit, which is interpreted as a float. This pull request replaces them by PHP_INT_MAX, which also has the …

Fix input to check_int. Use PHP_INT_MAX rather than hardcoded 4294967294

---

src/Module/Cli/UpdateCatalogCommand.php

This small change just checks for the "find" action in the run:updateCatalog command when deciding for the default actions to take. It was simply missing from the list.

Check for find action when deciding default actions

---

src/Repository/Model/Catalog.php
src/Repository/Model/Song.php

Debian Trixie here, with PHP8.4
Some warning in the logs
```
22  (log.lib) -> [Error] Ampache\Repository\Model\Catalog::cache_catalogs(): Implicitly marking parameter $interactor as nullable is deprecated, the explicit nullable type must be used instead in file src/Repository/Model/Catalog.php(1051)
22  (log.lib) -> [Error] Ampache\Repository\Model\Catalog::get_media_tags(): Implicitly marking parameter $file_override as nullable is deprecated, the explicit nullable type must be used instead in file src/Repository/Model/Catalog.php(3528)
22  (log.lib) -> [Error] Ampache\Repository\Model\Song::get_album_barcode(): Implicitly marking parameter $album_id as nullable is deprecated, the explicit nullable type must be used instead in file src/Repository/Model/Song.php(846)
22  (log.lib) -> …
```

Fix PHP8.4 errors

---

docker/Dockerfilephp82
docker/Dockerfilephp83
docker/Dockerfilephp84

Fixes an error message when running `docker compose up`:
```
1.810 E: Unable to locate package software-properties-common
```
Apparently this package is not part of Debian Trixie (the current Debian Stable) anymore:
https://packages.debian.org/search?searchon=sourcenames&keywords=software-properties

Fix "Unable to locate package software-properties-common" when building docker images
