ampache/ampache

lib/class/art.class.php
lib/class/catalog.class.php
lib/class/localplay.class.php
lib/class/plugin.class.php
lib/general.lib.php
modules/Auth/OpenID/FileStore.php
modules/captcha/captcha.php

see http://php.net/manual/en/function.readdir.php - specifically:
/* This is the correct way to loop over the directory. */
while (false !== ($entry = readdir($handle))) {
echo "$entry\n";
}
/* This is the WRONG way to loop over the directory. */
while ($entry = readdir($handle)) {
echo "$entry\n";
}

loop over directories the "correct" way

---

lib/javascript/ajax.js
lib/javascript/base.js
lib/javascript/search.js
lib/javascript/tools.js
locale/base/gather-messages.sh
modules/ampacheapi/AmpacheApi.lib.php
smartplaylist.php
sql/ampache.sql
templates/footer.inc.php
templates/show_web_player.inc.php

sorry for creating two pull requests for a minor change. I missed some lines the first time I did this.

change copyright years to 2015

---

lib/class/art.class.php
lib/class/catalog.class.php
lib/class/search.class.php
lib/class/update.class.php

Added width & height into table images
Added width & height search function for album original images
I needed this to identify albums with too small pictures.

Dimension info (width & height) for album images

---

templates/install_footer.inc.php

Fix for #680

---

lib/class/stream.class.php

And added it to $command to transcode.

Modified get_image_preview function to include a check that 'transcode_input' is defined

---

lib/class/vainfo.class.php

Cleaned "tv_episode" into $parsed['tvshow_episode'] to store episode number.

Added "case 'tv_episode':" to "function _cleanup_quicktime($tags)".

---

config/ampache.cfg.php.dist
lib/init.php
templates/footer.inc.php

Cleaned version of #702. This fixes #624.

(Cleaned) add option to show/hide footer statistics

---

templates/show_install.inc.php
templates/show_install_config.inc.php

Update any mysql password placeholders.
I did not notice that mysql password is required.

Update any mysql password placeholders

---

themes/reborn/templates/default.css

Solve #768

---

lib/class/catalog.class.php

I wonder how this was missed? ; ' >

Added return true; for successfuly deleted catalogs.

---

lib/class/api.class.php

The track isn't a playlist :) Changed it to scrub_in and I confirmed it worked locally via the XML API.

Fixed playlist_remove_song, it was improperly creating a playlist

---

lib/class/api.class.php
lib/class/xml_data.class.php

Relates to https://github.com/ampache/ampache/issues/851
I'm not a PHP developer, so I'm sorry if this is a crappy solution, but please feel free to critique :+1:

Return playlist track in the song XML if it is passed in

---

templates/show_album.inc.php

Add an "Add to existing playlist" button to Album UI

---

templates/jquery-editdialog.css
templates/show_html5_player.inc.php
templates/show_html5_player_headers.inc.php

This button is a bit nicer, has more functionality, and retains all old functionality :)

"Add to existing playlist" (and remove Add To New Playlist) via the html5 player

---

bin/channel_run.inc
lib/class/channel.class.php

- bin/channel_run.inc:
* extensive rewrite and restructuring
* implements a variable-size server-side buffer
* small bugfixes here and there
* allow for more precise bitrate handling (via $nb_chunks_remainder)
* small improvements to http serving
- lib/class/channel.class.php:
* add $header_chunk variable and remember header of current filer for later use in channel streaming
* added $chunk_size variable

Enables Ogg (also works with Opus) channel streaming

---

lib/class/stream.class.php

I realized that this (which I pulled before) but was somehow changed is exactly the other way round in the IF.
It's ok now with the change I made.

Bug detecting OS

---

locale/base/messages.pot
locale/base/translation-words.txt

The rest should be done by Transifex automatically :-)
I've also updated the Translation-words.txt
Write access to the locale directory would be nice :-P

POT-File update for Transifex

---

locale/base/TRANSLATIONS.md

Some small changes in Translations.md

---

locale/base/gather-messages.sh
locale/base/messages.pot
locale/base/translatable-database-strings.txt

+ Translation base catalog updated
+ `translation-words.txt` renamed to
`translatable-database-strings.txt`. It makes more sense and everyone knows where the strings within come from.
+ `gather-messages.sh` updated variables and switches + new header text for `translatable-database-strings.txt`
:-)

Translation base catalog updated + others

---

lib/class/song.class.php
lib/class/user.class.php

In my environment, the time it takes to open the top page:
Before: About 2.6s
After: About 0.08s

Improve performance around SQL query

---

config/ampache.cfg.php.dist
lib/class/catalog.class.php
lib/class/movie.class.php
lib/class/vainfo.class.php
lib/class/video.class.php
lib/init.php
modules/plugins/Tmdb.plugin.php
modules/plugins/Tvdb.plugin.php

Also increased version number of both Tmdb and Tvdb plugins.

Modified Tvdb and Tmdb plugins to correctly parse filenames.

---

templates/show_album_row.inc.php
templates/show_artist_row.inc.php
templates/show_broadcast_row.inc.php
templates/show_catalog_row.inc.php
templates/show_channel_row.inc.php
templates/show_edit_album_row.inc.php
templates/show_edit_artist_row.inc.php
templates/show_edit_share_row.inc.php
templates/show_edit_song_row.inc.php
templates/show_label_row.inc.php
templates/show_live_stream_row.inc.php
templates/show_now_playing_row.inc.php
templates/show_now_playing_video_row.inc.php
templates/show_object_row.inc.php
templates/show_playlist_row.inc.php
templates/show_playlist_song_row.inc.php
templates/show_search_row.inc.php
templates/show_share_row.inc.php
templates/show_song_preview_row.inc.php
templates/show_song_row.inc.php
templates/show_tvshow_row.inc.php
templates/show_tvshow_season_row.inc.php
templates/show_user_row.inc.php
templates/show_video_row.inc.php
templates/show_wanted_album_row.inc.php

+ Fixed consecutive php close and open tags ( ?> <?php )
+ Made some oneliner a little bit prettier

various formatting fixes on different *_row.inc.php

---

admin/users.php
locale/base/messages.pot

Fixed typo mentioned
on:
[https://www.transifex.com/.../48728143](https://www.transifex.com/ampache/ampache/translate/#cs_CZ/messagespot/48728143)
by
svetlemodry:
"Seems like a typo in the english source -> Avater"
Translation catalog
updated due to latest changes
:-)

Fixed Typo mentioned on transifex and updated lang catalog

---

lib/preferences.php
modules/Beets/Catalog.php
templates/show_edit_song_row.inc.php

As told in #1019 it looks like I missed some namespaces while refactoring.
This commit should fix it for the beets importer.

Fix case in lib namespace

---

lib/class/vainfo.class.php

Sorry about that.  I thought I cleaned the file before adding it to staging.

Cleaned merge info from vainfo.class.php.

---

lib/class/subsonic_api.class.php
lib/class/subsonic_xml_data.class.php

- For now just adds playcounts.  Could add other info in the future
- Right now only getAlbum.view, but other views that return song info could support this too.

Support an ampache=1 argument on getAlbum.view

---

lib/class/search.class.php

Adds the option to create smart playlists based on the tag of a song's parent album. This is the first of a couple of changes I'm planning to improve working with whole albums.

[FEATURE] Added 'album tag' option in song search

---

README.md

First it only was the fact that Ampache's dev-version was described as "It definitely will be unstable" at least in my thought. So I changed it to be a little bit ~~softer and then it got me.
Hate it? Love it? Let me know! ;-)

Improvements to let the readme look more personal

---

templates/show_login_form.inc.php

Another round for the scub_out function on the login page.

Remove scrub_out on login page's fields

---

lib/class/xml_data.class.php

`<playlisttrack>` tag does not appear in each items.
And errors occurred:
```
[Runtime Error] Invalid argument supplied for foreach()
```

Fix playlist_songs API

---

docs/man/man1/ampache.1

fixing according to:
https://lintian.debian.org/full/packages@qa.debian.org.html#ampache_3.6-rzb2752_x2bdfsg-7

fixing typo, as shown on litian.debian.org

---

lib/class/art.class.php
lib/class/core.class.php
modules/plugins/TheAudioDb/TheAudioDb.plugin.php

I recently noticed that some of the "gather art for artist" functions/plugins aren't giving any results.
This patch includes a fix for google picture search and for TheAudioDb plugin.
Further details are in my commit comments and of course in code ;)

Gather art fix

---

.travis.yml
lib/class/art.class.php
lib/class/catalog.class.php
lib/class/core.class.php
scripts/hooks/pre-commit
scripts/tests/codestyle.sh

* Fix php-cs according to https://github.com/ampache/ampache/issues/1251
to fix travis build. Use composer to force the 1.* version to be used.
* Add `encoding` fixer.
* Use the same set of fixers in Git commit hook and test script.
* Update hooks and scripts.
* Fix a braces issue detected by php-cs.
Closes issue #1251. Still waits for some issues upstream, listed in #1251.

Fix Travis-CI build

---

.gitignore
.php_cs

Sorry, I forgot to push this in latest PR =(

Use cache in PHPCs

---

lib/class/ldap.class.php

Stop using ARRAY_FILTER_USE_KEY which is PHP>=5.6

---

lib/class/art.class.php

Add the name of the album for which art generation failed in the log.
Closes #1178.

Fix for issue #1178

---

.github/ISSUE_TEMPLATE.md

Not sure if it is a better template or not. I tried to rework it a bit,
making use of HTML comments which are interpreted by Github to provide
extra information to the reporter, while not polluting resulting issue.
I also tried to remove the checkboxes templates which was resulting in
"1 out of 7 tasks done" in the issues list and could be misleading.
Let me know what you think about it.

Proposition of rework for issue template

---

lib/class/subsonic_api.class.php

The return value from `curl_exec` call in `Subsonic_API::follow_stream`
was not checked, leading to silent error when an incorrect URL was
provided (typically when `local_web_path` was not correctly set).
Also, the use of curl in `follow_stream` function was quite
counter-intuitive and unclear, I added a comment about it to help others
digging into the code.

DSub not playing music over Subsonic API, attempt to give more infos

---

composer.lock

Bump composer.lock to update xbmc-php-rpc version

---

lib/class/session.class.php
test.php

Introduce a "lang" cookie, and use it to translate `test.php`.
Closes #955.

Fix issue #955

---

lib/ui.lib.php

add support for unicode in notifications

---

lib/class/xml_data.class.php

Fixes the timeline function in the XML API.

Fix Timeline Function

---

locale/base/TRANSLATIONS.md

General Text overhaul, partially because of my changes on the gather script. Also some hits for commands and a reference to me for translation related questions.
:-)

Important changes

---

lib/class/xml_data.class.php
server/.htaccess

* Provide artists art in the `artists` method.
* Add `name` as an alias for `title` attribute for `songs` and stuff.
Closes #1292.

[WIP] Improve API, as discussed in #1292

---

locale/base/messages.pot
locale/base/translatable-database-strings.txt

POT Update related to #1342

---

composer.lock

Bump Guzzle version, mitigate HTTPOXY.

---

lib/class/api.class.php
lib/class/xml_data.class.php

* Remove `DEPRECATED` in API methods comments
WIP, don't merge right now please

API improvements

---

bin/write_playlists.inc

As reported in https://github.com/ampache/ampache/issues/405#issuecomment-244550648.

Do not force write_playlists.php to be called from bin folder

---

lib/class/catalog.class.php
lib/class/subsonic_xml_data.class.php

Add ignoredArticles to xml so they are still sorted properly
Fixes issue #1421

Use Artist full name (with prefix) in subsonic xml responses.

---

templates/show_recently_played.inc.php

"No recently item found" to "No recently played items found"

Minor grammar change

---

composer.json
lib/class/graph.class.php

Modified composer.json to correctly install .js files.

Upload fix

---

templates/show_install_config.inc.php

fix for web_path auto configuration for subdirectory installation
#1584

fix for web_path auto configuration for subdirectory installation

---

lib/class/song.class.php

When i verify a catalog and a song has changed its composer tag, ampache detects it but didnt update the database, so i make this changes and now is working.
i have little knowledge about sql, so please review the changes.
Thankyou.

Composer tag changes are not written on database

---

modules/catalog/seafile/seafile.catalog.php

catch null reference

---

locale/base/messages.pot

Totaly forgot to recreate the pot file for the source translation
strings.
But here it is.
:-)

Addendum to #1632

---

locale/base/messages.pot
modules/catalog/dropbox/dropbox.catalog.php

Small correction.
That's what happens when you think, copy and pasting is an easy task and fail.

Another addendum to #1632

---

lib/class/search.class.php
modules/captcha/captcha.php
modules/oauth/OAuth.php

I'm sorry if this has caused problems in the tree, i reforked and remerged into current develop.
Then ran phpfixer over the top
~~~
user@df2106:~/tmp/ampache/lib/class$ php-cs-fixer fix -v ./search.class.php 
Loaded config default.
.
Legend: ?-unknown, I-invalid file syntax, file ignored, S-Skipped, .-no changes, F-fixed, E-error
Fixed all files in 0.200 seconds, 14.000 MB memory used
~~~

rebase of search changes for pull #1544

---

templates/base.css
templates/header.inc.php

I wanted to make the code in the `header.inc.php` more reader friendly.
I guess the php cs fixer doesn't like reader friendlyness. For pure PHP
the CS fixer may be a great solution. But for mixed PHP HTML it's not that great...
Anyways, this Fixes #1461
:-)

Fix for #1461

---

lib/class/plex_api.class.php
lib/class/subsonic_api.class.php
lib/class/xml_data.class.php

add LIBXML_PARSEHUGE

---

config/ampache.cfg.php.dist
lib/class/album.class.php
lib/class/artist.class.php
lib/class/rating.class.php
lib/class/search.class.php
lib/class/song.class.php
lib/class/waveform.class.php
lib/log.lib.php
lib/preferences.php
modules/catalog/soundcloud/soundcloud.catalog.php
server/ajax.server.php
server/stream.ajax.php
server/tag.ajax.php
stream.php
templates/base.css
templates/jplayer.midnight.black-iframed.css
templates/jplayer.midnight.black.css
templates/jquery-editdialog.css
templates/jquery-file-upload.css
themes/reborn/templates/default.css

Final code issue update, now it's onto the project tasks and bug fixes from all the wild changes.

Core update 6

---

lib/class/art.class.php
lib/class/recommendation.class.php
templates/show_html5_player.inc.php
themes/reborn/templates/default.css

* Don't show webplayer action buttons on mobile
* Update the header useragent in art.class
* Fix #1865 opened by @a7medo778
* Fix a UI bug where chrome was not showing the rightbar properly

Core Update 17

---

bin/install/add_user.inc

This is a simple pull request fixing a small typo in the bin/install/add_user.in script.

fix a possible small typo

---

lib/class/privatemsg.class.php
lib/class/stream_playlist.class.php
lib/class/update.class.php
modules/catalog/seafile/SeafileAdapter.php
modules/catalog/seafile/composer.module.json
modules/catalog/seafile/seafile.catalog.php
pvmsg.php

This seems to have affected people using ampache since 3.6 when subcategories were introduced.
@apastuszak can you tell me what options are missing for you comparing your old preferences table to the new one?
I would also compare the two user_preference tables as well.

Update database for older users

---

lib/class/search.class.php
lib/class/stream.class.php
lib/class/user.class.php
server/stream.ajax.php

Lachlan-00 patch 1

---

index.php
lib/class/catalog.class.php
lib/class/session.class.php
lib/class/song.class.php
lib/class/stream.class.php
play/index.php

I noticed my files were transcoding to the file bitrate instead of what i set it to be.

use user_transcode bitrates instead of file bitrate

---

lib/class/api.class.php
lib/class/stats.class.php
lib/class/userflag.class.php

fix for #1973
fix for #1974
extra code checks for #1971

extend stats in api, bugfixes

---

lib/class/user.class.php

query tables that exist.
fix query structure

close #1995

---

register.php
templates/header.inc.php
templates/show_login_form.inc.php
templates/show_lostpassword_form.inc.php
templates/show_registration_confirmation.inc.php
templates/show_song.inc.php
templates/show_user_registration.inc.php
themes/reborn/templates/dark.css
themes/reborn/templates/default.css
themes/reborn/templates/light.css

These fixes should solve the problems in #1990 and #1988, and I have to say, it looks beautiful now! Unfortunately it probably wont get much use but such is life.
Some shots of what it looks like:

Fix registration page styles

---

bin/catalog_update.inc
bin/write_playlists.inc
docs/CHANGELOG.md
lib/class/catalog.class.php

Look for updated artist information. (missing or < 6 months since last update)
Update similar artists from local artists as well
**Requires last.fm apikey**

add -u to bin/catalog_update.inc

---

lib/class/update.class.php
templates/error_page.inc.php
templates/install_header.inc.php
templates/show_test.inc.php
templates/test_error_page.inc.php
update.php

The changes from my last pull request, adds 'For the Love of Music' as a string, and adds a couple others.

add for the love of music, and added some missing

---

lib/class/art.class.php

hey @stebe can you put any more info about that art error here?
One of the first things i've noticed is that will will try to destroy the image even if it's failed so we shouldn't do that.
My server has hit up so many api's that i'm getting limited on art searches now.

only fail php-gd check once

---

lib/class/catalog.class.php
lib/class/song.class.php
server/catalog.ajax.php

need to rotate the update time more often to reflect changes elsewhere as this is the only table that has an update time

Update song.update_time when artist/album change

---

templates/show_login_form.inc.php

forgot password link disappeared

fix bug from #2016

---

lib/class/privatemsg.class.php
lib/class/registration.class.php
lib/class/shoutbox.class.php

Noticed some strings that should probably be cleaned up. Not sure if I did it in the best way, feel free to fix up.

Cleanup multi-line strings

---

lib/class/ampache_rss.class.php
lib/class/autoupdate.class.php
lib/class/share.class.php
lib/javascript/dynamicpage.js
modules/plugins/Flattr/Flattr.plugin.php
templates/header.inc.php
templates/rightbar.inc.php
templates/show_account.inc.php
templates/show_album.inc.php
templates/show_album_group_disks.inc.php
templates/show_album_row.inc.php
templates/show_artist.inc.php
templates/show_login_form.inc.php
templates/show_playlist.inc.php
templates/show_playlist_media_row.inc.php
templates/show_playlist_row.inc.php
templates/show_podcast_episode.inc.php
templates/show_podcast_episode_row.inc.php
templates/show_search.inc.php
templates/show_search_options.inc.php
templates/show_search_row.inc.php
templates/show_song.inc.php
templates/show_song_row.inc.php
templates/show_video.inc.php
templates/show_video_row.inc.php
templates/sidebar.inc.php
templates/sidebar.light.inc.php

Resubmitted because somehow I had some extra files. But seems to be working!

Change rel="nohtml" to a class

---

lib/class/catalog.class.php
lib/class/subsonic_api.class.php

code wasn't using the count correctly and has been restored

fix Subsonic getnewestpodcasts

---

lib/class/access.class.php
lib/class/graph.class.php
lib/class/random.class.php
lib/class/stats.class.php
lib/class/subsonic_api.class.php
lib/class/subsonic_xml_data.class.php
lib/class/xml_data.class.php
modules/plugins/MusicBrainz/MusicBrainz.plugin.php
templates/show_album.inc.php
templates/show_artist.inc.php

copy/paste with translations broke the artist count by looking for an album.

fix object_count on artist pages, reduce some code duplication

---

docs/CHANGELOG.md
lib/class/api.class.php
lib/class/podcast_episode.class.php
lib/class/song.class.php
play/index.php
templates/show_get_art.inc.php

allow raw downloads from api and play/index, tetnative art search bugfix

---

themes/reborn/templates/dark.css
themes/reborn/templates/default.css
themes/reborn/templates/light.css

A lot of prefixes in the CSS should be removed in my opinion. `box-shadow` for example has 99.5% unprefixed support(https://www.caniuse.com/#search=box-shadow)

Cleanup Reborn theme CSS

---

lib/class/json_data.class.php

It took me more time to figure out how to use Git than to make these fixes.

Removes  unnecessary Arrays. Fixes art for songs()

---

bin/clean_art_table.inc
lib/class/art.class.php
lib/class/artist.class.php
lib/class/stats.class.php
lib/class/stream.class.php

clean the image table when art is outside the minimum or maximum settings in your config file

 bin/clean_art_table.inc

---

lib/class/search.class.php
lib/class/song.class.php

split basetypes out of construct and search types into their own functions.

make search a bit clearer

---

lib/class/channel.class.php
lib/class/graph.class.php
lib/class/label.class.php
lib/class/search.class.php
lib/class/shoutbox.class.php
lib/class/tag.class.php
server/playlist.ajax.php

New Album searches
time, artistrating
New Artist searches
image_height, image_width
New Artist and Album Searches
played_times, favorite

Scrutinizer, tag fixes, lots of search additions

---

templates/show_test.inc.php

Missing underscore from the translation function.

Fix typo in show_test.inc.php

---

lib/class/api.class.php
lib/class/xml_data.class.php

This fix th ID not showing on the XML file when you create a new playlist with an API Client

playlist_create suggested changes

---

lib/class/json_data.class.php

Add favorite flag

---

lib/class/api.class.php

Implementing feature request https://github.com/ampache/ampache/issues/2285

Xml api: filter parameter is optional for songs

---

lib/class/xml_data.class.php

This time I also removed a space before `++`.

Remove unnessary null checks V2

---

lib/class/subsonic_api.class.php
lib/class/waveform.class.php

api subsonic playlist delete/add

---

composer.json
lib/class/json_data.class.php

Some things still missing though, marked with TODO.
There may be some breaking changes.

Cleaned up json_data.class.php and brought to parity with XML. 

---

lib/class/json_data.class.php
lib/class/xml_data.class.php

Simply adds the play count to the API.

Add PlayCount to API

---

lib/class/podcast_episode.class.php
lib/class/song.class.php
lib/class/stream_playlist.class.php
lib/class/video.class.php
play/index.php
templates/show_recently_played.inc.php
templates/show_song.inc.php

@stebe i see the session part was wrong in play/index url, this fixes the urls correctly for mpd

Play url users

---

modules/catalog/local/local.catalog.php

remove trailing slash when adding new files from subdirectory

---

lib/class/catalog.class.php
lib/class/song.class.php

truncate song title to max 255 bytes, before insert into db

---

lib/javascript/search.js

correctly remove metadata field (subtype) select list

---

lib/class/search.class.php

remove group on artist when searching by artist in songs

---

lib/class/search.class.php

Proposal for feature request #2414

add search in lyrics

---

lib/class/vainfo.class.php

Allow ID3v2 TXXX tags to be imported. Proposal for #2418

Txxx metadata

---

lib/class/search.class.php

Proposal for #2420 
Using the search on this screenshot:
MariaDB [ampache]> SELECT DISTINCT(`song`.`id`) FROM `song` LEFT JOIN `metadata` AS metadata5ee8b20224b55 ON `song`.`id` = `metadata5ee8b20224b55`.`object_id` LEFT JOIN `metadata` AS metadata5ee8b20224c5c ON `song`.`id` = `metadata5ee8b20224c5c`.`object_id` WHERE (`metadata5ee8b20224b55`.`field` = 31 AND `metadata5ee8b20224b55`.`data` LIKE "%nick%") OR (`metadata5ee8b20224c5c`.`field` = 31 AND `metadata5ee8b20224c5c`.`data` LIKE "%bad%");
+-------+
| id    |
+-------+
+-------+
**160 rows in set (13 min 32.234 sec)**
MariaDB [ampache]> EXPLAIN EXTENDED SELECT DISTINCT(`song`.`id`) FROM `song` LEFT JOIN `metadata` AS metadata5ee8b20224b55 ON `song`.`id` = `metadata5ee8b20224b55`.`object_id` LEFT JOIN `metadata` AS …

improve speed of metadata queries

---

play/index.php

save_mediaplay isn't called when udate_stats was removed.

Fix for songs not scrobbling

---

lib/class/api.class.php

Fetch with "filter" paramter is correct again.
API functions "playlist" and "playlist_songs" are fixed.

API fix: playlist "filter" parameter

---

templates/header.inc.php
templates/show_get_art.inc.php

This works whether AJAX load is enabled or not.

Returned correct functionality to 'Cancel' button of 'show get art' dialog

---

templates/jplayer.midnight.black-iframed.css

I there,
I updated the current song's color to be more visible. It seems it was like that back in the time.
Have a nice day and stay safe.

Player's current song color updated

---

lib/class/song.class.php
lib/class/update.class.php

If metadata wasn't already in file tag, the frame wouldn't be written.

Bug. wouldn't write certain metadata.

---

config/ampache.cfg.php.dist

Just a typo here.
Have a nice day and stay safe.

Fixing typo

---

themes/reborn/templates/default.css

Hi there,
Another quick login page style update.
Before:
After:
Stay safe and have a nice day.

Login page centered content

---

templates/show_recently_played.inc.php

Just an extra closing tag removed.
Have a nice day.

Extra td closing tag removed from show recently played

---

lib/class/search.class.php

I have albums that consists of multiple disks.
I want to display them in disk number order.

Order by name and disk when searching album

---

client/Views/Albums/index.styl
client/Views/Albums/index.tsx
client/logic/Album.ts
client/router.tsx

Implented the albums page following the same structure used for artists.
Before:
After:

Albums page

---

client/stylus/main.styl

Custom scrollbar styling, before & after

Custom scrollbar colors

---

rest/index.php

https://github.com/ampache/ampache/issues/2692

The default format for the Subsonic API should be XML

---

public/themes/reborn/templates/default.css

A little usability improvement

Indicate currently active sidebar tab

---

graph.php
image.php
lib/class/ApiMethods/GoodbyeMethod.php
lib/class/ApiMethods/HandshakeMethod.php
lib/class/ApiMethods/PingMethod.php
server/xml.server.php

Stop logging auth/passphrase strings

---

lib/class/catalog.class.php

Fixes #2745
Regression introduced in: f698dbb

Correct parameter name

---

public/themes/reborn/templates/default.css

Maintain column widths during table sort

---

public/templates/list_header.inc.php
public/templates/show_html5_player.inc.php

Also add href to the webplayer actions that didn't have them, just for consistency

Prevent page jump on View click

---

client/Contexts/MusicContext.tsx
client/Views/App.tsx
client/components/MusicControl.tsx
client/components/Rating/index.tsx
client/components/SongRow/index.tsx

Added the ability to flag songs as favorites both from the song row (see gif) and from the music controller bar.

Added favorite feature for songs

---

locale/base/messages.pot
locale/base/translatable-database-strings.txt

Translation Update March 2021-2

---

public/templates/header.inc.php
public/templates/stylesheets.inc.php

`Ui:-:find_template` couldn't find them, so directly used `$web_path` and moved them to "stylesheets.inc,php".

Two CSS files for jquery dialogs weren't being found.

---

config/ampache.cfg.php.dist
src/Config/ConfigurationKeyEnum.php
src/Config/Init/InitializationHandlerConfig.php
src/Module/Util/ZipHandler.php

Closes #1365 add art
Closes #1245 add m3u, preserve filestructure
Open Encoding issues  with accentuated characters

Extend Ziphandler add abilility to add art and m3u

---

public/templates/show_html5_player_headers.inc.php
src/Config/functions.php

Silent notifications + bonus typo fix

---

composer.json
composer.lock
public/templates/header.inc.php
public/templates/show_html5_player.inc.php
public/templates/show_html5_player_headers.inc.php
public/templates/sidebar.inc.php

Replaced jquery-cookie with js-cookie

---

public/templates/show_playlist.inc.php

in my opinion this part is missing when editing a play list

make "share playlist" appear in play list edit

---

src/Repository/Model/Random.php

Fix Error SQL (1052) : Column 'time' in field list is ambiguous when creating a random song playlist.

Fix random song playlist SQL error

---

.gitignore
.php_cs
.phpcs.xml

Prepping for Ample web client release 🎉

exclude Ample client from repo

---

public/templates/show_arts.inc.php
src/Module/Api/Upnp_Api.php
src/Module/Application/Login/DefaultAction.php
src/Module/Cli/AdminAddUserCommand.php
src/Module/System/Session.php
src/Module/Util/OAuth/OAuthRequest.php

replace mt_rand with random_bytes

---

src/Repository/AlbumRepository.php

fixes incorrect SQL (missing WHERE) for some cases.

fix SQL for random selection of albums

---

public/templates/list_header.inc.php

Update View > Limit once focus moves away, instead of after key up

---

resources/templates/album_row.xhtml
src/Gui/Album/AlbumViewAdapter.php
src/Gui/Album/AlbumViewAdapterInterface.php
tests/Gui/Album/AlbumViewAdapterTest.php

Missed $display_year condition at top of legacy template

Restore original year for album if enabled

---

src/Repository/Model/Album.php

Check data, avoid runtime error in logs.

check empty data, avoid runtime error

---

src/Module/Art/Collector/ArtCollector.php

Increase ART_SEARCH_LIMIT to 15, closes #3126

increase art limit

---

src/Module/Playback/Localplay/Xbmc/AmpacheXbmc.php

Changes to follow localplay guidelines

Follow localplay guidelines

---

src/Module/Api/Daap_Api.php

Reverse to old code, working only for songs, but at least creates a working url.

First patch to make daap working again

---

src/Module/Playback/Localplay/Xbmc/AmpacheXbmc.php

Correct status function in localplay xbmc to return the correct values to the localplay api

Fix status to match localplay api

---

src/Module/Api/Daap_Api.php

Little hack ( force uid = -1 ) to make daap working again, tested with rhythmbox with no issues

Daap working again

---

resources/templates/stats.xhtml

Remove user column from the statistics table

---

public/templates/show_add_filter.inc.php
public/templates/show_add_user.inc.php
src/Module/Application/Admin/Filter/AddFilterAction.php

Made DEFAULT the default filter for a new user (0 vs 1 numbering).
Removed an errant comment.
Closes #3306

Fix catalogs not being saved properly on filter creation.

---

public/templates/footer.inc.php

Updated copyright year from 2020 to 2022 in footer.inc.php.

Update copyright year in footer.inc.php

---

src/Module/Art/Collector/MetaTagCollectorModule.php
src/Repository/Model/Art.php

Sort found art in tags by a priority list (album or artist).
Refactor to remove some duplicate code to gather art in tags which also addresses in a different way #3537.

Prefer cover art when gathering art from embedded tags

---

src/Module/User/Registration.php

Added an urlencode on username

Fix validate url provided in validation email: handle all username

---

phpstan-baseline.neon
phpstan.neon
src/Application/Api/Ajax/Handler/TagAjaxHandler.php
src/Module/Application/Batch/DefaultAction.php
src/Repository/Model/Art.php
src/Repository/Model/Catalog.php
src/Repository/Model/Shoutbox.php

Perhaps you should consider including the stan-checks in the `composer qa` command. It's a bit annoying to be constantly reminded of type issues, but on the other hand it's a big win for type safety in the long run.

Correct some typing issues and update stan baseline

---

composer.json
phpstan-baseline.neon
src/Module/Api/Method/Api5/SystemPreferences5Method.php
src/Module/Api/Method/Api5/UserPreferences5Method.php
src/Module/Api/Method/SystemPreferencesMethod.php
src/Module/Api/Method/UserPreferencesMethod.php
src/Module/Application/Admin/User/ShowPreferencesAction.php
src/Repository/Model/Preference.php
src/Repository/Model/User.php
src/Repository/PreferenceRepository.php
src/Repository/PreferenceRepositoryInterface.php
src/Repository/service_definition.php
tests/Module/Application/Admin/User/ShowPreferencesActionTest.php

Also add the PreferenceRepository which manages preference-related database actions

Add tests for admin user ShowPreferencesAction

---

public/templates/show_add_filter.inc.php
public/templates/show_add_user.inc.php
public/templates/show_edit_filter.inc.php

This fixes at least an issue related to adding avatars when creating new users

Correct form encding in several locations

---

phpstan-baseline.neon
src/Repository/Model/Album.php
src/Repository/Model/AlbumDisk.php
src/Repository/Model/Artist.php
src/Repository/Model/Song.php

I was not able to find usages of those symbols, so remove it.

Remove unused methods

---

public/templates/show_add_catalog.inc.php
public/templates/show_catalog_row.inc.php
public/templates/show_manage_catalogs.inc.php
src/Module/Application/Admin/Catalog/ShowCatalogsAction.php
src/Repository/Model/Catalog.php

- Rename $libitem -> $catalog
- Move catalog-type rendering from Catalog into the show_add_catalog template
Related ea3c660157d5234e21f9e60f0295e6fb83d7ca76

Correct catalog list rendering

---

phpstan-baseline.neon
src/Module/Api/Edit/EditObjectAction.php
src/Repository/Model/Share.php
src/Repository/Model/Wanted.php

Also remove post-update item formatting as the action returns just the object id (which is always the same cause it's an edit-action)
Related #3676

Respect the special requirements of Share::update()

---

phpstan-baseline.neon
src/Module/Api/Xml_Data.php
src/Module/Application/Rss/ShowAction.php
src/Module/Playback/Stream.php
src/Module/Util/AmpacheRss.php
src/Module/Util/AmpacheRssInterface.php

This will help the static analysis to reach the data-loading-methods

Replace static rss loading methods

---

src/Module/Api/Json4_Data.php
src/Module/Api/Json5_Data.php
src/Module/Api/Json_Data.php
src/Module/Api/Method/Api3/LastShouts3Method.php
src/Module/Api/Method/Api4/LastShouts4Method.php
src/Module/Api/Method/Api5/LastShouts5Method.php
src/Module/Api/Method/LastShoutsMethod.php
src/Module/Api/Xml3_Data.php
src/Module/Api/Xml4_Data.php
src/Module/Api/Xml5_Data.php
src/Module/Api/Xml_Data.php
src/Module/Util/AmpacheRss.php
src/Plugin/AmpacheShoutHome.php
src/Repository/Model/Shoutbox.php
src/Repository/ShoutRepository.php
src/Repository/ShoutRepositoryInterface.php
tests/Repository/ShoutRepositoryTest.php

Also use a Generator where applicable

Move Shoutbox::get_top into repository

---

phpstan-baseline.neon
src/Config/DicBuilder.php
src/Module/Application/Shout/AddShoutAction.php
src/Module/Database/DbaDatabaseConnection.php
src/Module/Shout/ShoutCreator.php
src/Module/Shout/ShoutCreatorInterface.php
src/Module/Shout/service_definition.php
src/Repository/Model/Shoutbox.php
src/Repository/ShoutRepository.php
src/Repository/ShoutRepositoryInterface.php
tests/Module/Shout/ShoutCreatorTest.php
tests/Repository/ShoutRepositoryTest.php

This simplifies creating new shouts and improves testability. More refactoring incoming...

Move shout creation into a single class

---

phpstan-baseline.neon
public/templates/show_edit_shout.inc.php
src/Module/Application/Admin/Shout/ShowEditAction.php
src/Repository/Model/PrivateMsg.php
src/Repository/Model/Shoutbox.php
src/Repository/Model/User.php

Also update the getter-method and remove some calls to User::format()

Make User::f_link private

---

src/Repository/Model/ModelFactory.php

Since e990369 the constructors handling of the object-id within the model class has changed.

Add implicit object-id type casts in ModelFactory

---

public/templates/show_add_shout.inc.php
src/Application/Api/Ajax/Handler/SongAjaxHandler.php
src/Module/Application/Shout/ShowAddShoutAction.php
src/Module/Shout/ShoutRenderer.php
src/Module/Shout/ShoutRendererInterface.php
src/Module/Shout/service_definition.php
src/Plugin/AmpacheShoutHome.php
src/Repository/Model/Catalog.php
src/Repository/Model/Shoutbox.php
src/Repository/Model/Song.php
src/Repository/Model/TvShow.php
src/Repository/ShoutRepository.php
src/Repository/ShoutRepositoryInterface.php
tests/Repository/ShoutRepositoryTest.php

This moves the migrate-method into the ShoutRepository and the rendering-method into a standalone class. Almost done...

Extract migration- and rendering-methods from Shoutbox

---

public/templates/show_manage_shoutbox.inc.php
src/Module/Application/Admin/Shout/ShowEditAction.php
src/Module/Application/Shout/AddShoutAction.php
src/Module/Application/Shout/ShowAddShoutAction.php
src/Module/Shout/ShoutObjectLoader.php
src/Module/Shout/ShoutObjectLoaderInterface.php
src/Module/Shout/ShoutRenderer.php
src/Module/Util/AmpacheRss.php
src/Repository/Model/Browse.php
src/Repository/Model/Shoutbox.php

This removes the last static method from the Shoutbox model

Extract object loading from Shoutbox model item

---

phpstan-baseline.neon
src/Module/Application/Admin/Shout/ShowEditAction.php
src/Module/Cli/PrintTagsCommand.php
src/Repository/ShoutRepository.php
tests/Module/Application/Admin/Shout/ShowEditActionTest.php

Also fix a small stan issue which came up after the recent stan update

Add tests for shout ShowEditAction

---

phpstan-baseline.neon
src/Module/Application/Admin/Mail/SendMailAction.php
src/Module/Cli/PrintTagsCommand.php
src/Module/Shout/ShoutCreator.php
src/Module/User/NewPasswordSender.php
src/Module/User/PrivateMessage/PrivateMessageCreator.php
src/Module/User/Registration.php
src/Module/User/UserStateToggler.php
src/Module/Util/Mailer.php
src/Module/Util/MailerInterface.php
src/Repository/Model/Preference.php
src/Repository/Model/User.php
tests/Module/Shout/ShoutCreatorTest.php
tests/Module/User/UserStateTogglerTest.php

This allows to write test expectations...

Add setter for the Mailer-class

---

phpstan-baseline.neon
public/templates/show_debug.inc.php
public/templates/show_localplay_status.inc.php
src/Config/functions.php
src/Module/Application/LostPassword/ShowAction.php
src/Module/Util/Ui.php
src/Module/Util/VaInfo.php

Hopefully, we can get rid of those global methods in functions.php some day...

Move some global methods into classes

---

phpstan-baseline.neon
public/templates/show_export.inc.php
src/Module/Application/Admin/Export/ExportAction.php
src/Module/Application/Admin/Export/ShowAction.php
src/Module/Catalog/CatalogLoader.php
src/Module/Catalog/CatalogLoaderInterface.php
src/Module/Catalog/Exception/CatalogLoadingException.php
src/Module/Catalog/Export/CatalogExportFactory.php
src/Module/Catalog/Export/CatalogExportFactoryInterface.php
src/Module/Catalog/Export/CatalogExportTypeEnum.php
src/Module/Catalog/Export/CatalogExporterInterface.php
src/Module/Catalog/Export/CsvExporter.php
src/Module/Catalog/Export/ItunesExporter.php
src/Module/Catalog/service_definition.php
src/Repository/Model/Catalog.php
src/Repository/SongRepository.php
src/Repository/SongRepositoryInterface.php
tests/Module/Application/Admin/Export/ExportActionTest.php
tests/Module/Application/Admin/Export/ShowActionTest.php
tests/Module/Catalog/Export/CatalogExportFactoryTest.php
tests/Repository/SongRepositoryTest.php

Split up itunes and csv export, make the download-headers actually work

Extract catalog exporting from Catalog class

---

src/Application/Api/Ajax/Handler/PodcastAjaxHandler.php
src/Module/Api/Subsonic_Api.php
src/Module/Podcast/Exception/PodcastFolderException.php
src/Module/Podcast/PodcastCreator.php
src/Module/Podcast/PodcastEpisodeDownloader.php
src/Module/Podcast/PodcastEpisodeDownloaderInterface.php
src/Module/Podcast/PodcastFolderProvider.php
src/Module/Podcast/PodcastFolderProviderInterface.php
src/Module/Podcast/PodcastSyncer.php
src/Repository/Model/Podcast.php
src/Repository/Model/Podcast_Episode.php
tests/Module/Podcast/PodcastCreatorTest.php

This extracts some features into separate classes to enhance testability

Extract podcast folder building and episode downloading

---

src/Config/ConfigurationKeyEnum.php
src/Module/Api/Method/Api4/PodcastDelete4Method.php
src/Module/Api/Method/Api5/PodcastDelete5Method.php
src/Module/Api/Method/PodcastDeleteMethod.php
src/Module/Api/Subsonic_Api.php
src/Module/Application/Podcast/ConfirmDeleteAction.php
src/Module/Application/PodcastEpisode/ConfirmDeleteAction.php
src/Module/Podcast/PodcastDeleter.php
src/Module/Podcast/PodcastDeleterInterface.php
src/Module/Podcast/PodcastFolderProvider.php
src/Module/Podcast/PodcastSyncer.php
src/Repository/Model/Catalog.php
src/Repository/Model/Podcast.php
src/Repository/Model/Podcast_Episode.php
src/Repository/PodcastRepository.php
src/Repository/PodcastRepositoryInterface.php
tests/Module/Application/Podcast/ConfirmDeleteActionTest.php
tests/Module/Podcast/PodcastFolderProviderTest.php
tests/Repository/PodcastRepositoryTest.php

This reduces the podcast and -episode classes a bit more...

Extract methods for podcast and -episode deletion

---

src/Module/Api/Subsonic_Xml_Data.php
src/Repository/Model/Catalog.php

The most recent phpstan version updates the SimpleXmlElement method signatures...

Add mitigation for the recent found stan issues

---

phpstan-baseline.neon
src/Module/Album/Deletion/AlbumDeleter.php
src/Repository/AlbumRepository.php
src/Repository/AlbumRepositoryInterface.php
src/Repository/Model/Album.php
src/Repository/Model/Catalog.php
src/Repository/Model/Song.php
tests/Repository/AlbumRepositoryTest.php

- Add some tests for existing methods
- Remove some unused methods

Move some method from Album to AlbumRepository

---

phpstan-baseline.neon
src/Module/Api/Subsonic_Api.php
src/Module/Playback/Stream_Playlist.php
src/Module/Playback/Stream_Url.php
src/Module/Playlist/PlaylistExporter.php
src/Repository/Model/Playlist.php
src/Repository/Model/playlist_object.php

Also add some more checks, type hints, ...

Correct type issues in Stream_Playlist

---

phpstan-baseline.neon
public/templates/show_user_registration.inc.php
src/Module/Application/Register/AddUserAction.php
src/Module/Application/Register/ShowAddUserAction.php
src/Module/User/Registration.php
src/Module/User/Registration/RegistrationAgreementRenderer.php
src/Module/User/Registration/RegistrationAgreementRendererInterface.php
src/Module/User/service_definition.php
tests/Module/User/Registration/RegistrationAgreementRendererTest.php

Use a dedicated renderer to show the registration agreement

---

phpstan-baseline.neon
phpunit.xml.dist
src/Module/Api/Method/Api4/ShareEdit4Method.php
src/Module/Api/Method/Api5/ShareEdit5Method.php
src/Module/Api/Method/ShareEditMethod.php
src/Module/Application/Admin/Catalog/AddCatalogAction.php
src/Module/Application/Admin/Filter/AddFilterAction.php
src/Module/Application/Admin/Filter/ShowAddFilterAction.php
src/Module/Application/Admin/Filter/ShowEditAction.php
src/Module/Application/Admin/Filter/UpdateFilterAction.php
src/Module/Application/Admin/License/EditAction.php
src/Module/Application/Admin/User/AddUserAction.php
src/Module/Application/Admin/User/UpdateUserAction.php
src/Module/Application/PrivateMessage/AddMessageAction.php
src/Module/Application/Register/AddUserAction.php
src/Module/Wanted/MissingArtistFinder.php

It's deprecated, so we'd like to get rid of it

Replace all remaining occurrences of FILTER_SANITIZE_STRING

---

public/podcast.php
public/templates/show_podcasts.inc.php
resources/templates/podcast/export.opml
src/Module/Application/Podcast/ExportPodcastsAction.php
src/Module/Application/service_definition.php
src/Module/Podcast/Exchange/PodcastExporterInterface.php
src/Module/Podcast/Exchange/PodcastOpmlExporter.php
src/Repository/PodcastRepository.php
src/Repository/PodcastRepositoryInterface.php
tests/Module/Application/Podcast/ExportPodcastsActionTest.php
tests/Module/Podcast/Exchange/PodcastOpmlExporterTest.php
tests/Repository/PodcastRepositoryTest.php

This adds the podcast opml export as described in #3737

Add podcast opml export

---

src/Module/Playback/Localplay/Xbmc/AmpacheXbmc.php

* Pause status ( using speed = 0 )
* Correct behaviour of play/stop/pause
* More robust skip function ( to handle subsonic jukebox )
* Status bugs fixed, status function now follows localplay api

XBMC localplay improvements

---

phpstan-baseline.neon
src/Module/Util/Ui.php
src/Repository/MetadataFieldRepository.php
src/Repository/MetadataFieldRepositoryInterface.php
src/Repository/Model/Search.php
src/Repository/Repository.php
tests/Repository/MetadataFieldRepositoryTest.php

Add a method to the new repo to keep the functionality

Remove MetadataFieldRepository::findAll

---

composer.json
phpstan-baseline.neon
src/Module/Api/DaapApiApplication.php
src/Module/Util/Ui.php
src/Repository/Model/Search.php

Also fix scn/phptal to the new major branch 4 instead of using master

Correct some type issues due to the recent phpstan update

---

public/templates/show_edit_podcast_row.inc.php
src/Module/Api/Edit/EditObjectAction.php
src/Module/Api/Method/Api4/PodcastEdit4Method.php
src/Module/Api/Method/Api5/PodcastEdit5Method.php
src/Module/Podcast/Feed/FeedLoader.php
src/Module/Podcast/Feed/FeedLoaderInterface.php
src/Module/Podcast/PodcastCreator.php
src/Module/Util/Ui.php
src/Repository/Model/Podcast.php
src/Repository/Model/Search.php
src/Repository/PodcastRepository.php
src/Repository/PodcastRepositoryInterface.php
tests/Repository/Model/PodcastTest.php
tests/Repository/PodcastRepositoryTest.php

Make use of the new podcast setter-methods to update data. Also let the model truncate too long strings instead of doing this every time we get some input in our hands.

Remove usages of Podcast::update()

---

.scrutinizer.yml

That should help, related to #3790

Set scrutinizer memory-limit to indefinite

---

src/Module/Api/Subsonic_Xml_Data.php
src/Module/Playback/Localplay/Vlc/AmpacheVlc.php
src/Module/Playback/Localplay/Xbmc/AmpacheXbmc.php

* Correct bugs in localplay VLC and XBMC
* Enable index in every localplay client ( clients have to handle it )
* Add sleep in XBMC function to handle delay in kodi client response

Localplay and jukebox mode improvements ( Vlc and Xbmc )

---

src/Repository/Model/Tag.php

This should speed things up...

Re-arrange the tag-count retrieval query

---

src/Module/Podcast/PodcastSyncer.php
src/Repository/PodcastRepository.php
src/Repository/PodcastRepositoryInterface.php
tests/Repository/PodcastRepositoryTest.php

The repo method should not care about limits, this is the business-layers job...

Move podcast episode download limit retrieval into PodcastSyncer

---

src/Module/Playback/Localplay/Vlc/AmpacheVlc.php

Various improvements to ampachevlc
* localplay api compliant
* fix runtime error in get function
* support vlc api 1 and api 3

Vlc localplay improvements

---

src/Module/Application/Admin/License/DeleteAction.php
src/Module/Application/Admin/License/EditAction.php
src/Module/Application/Admin/License/ShowAction.php
src/Repository/LicenseRepository.php
src/Repository/LicenseRepositoryInterface.php
src/Repository/Model/License.php
src/Repository/Model/Search.php
tests/Module/Application/Admin/License/DeleteActionTest.php
tests/Module/Application/Admin/License/EditActionTest.php
tests/Module/Application/Admin/License/ShowActionTest.php
tests/Repository/LicenseRepositoryTest.php

Add tests for every method in there

Rework the LicenseRepository

---

composer.json
rector.php
tests/Module/Application/Podcast/ShowActionTest.php

Also adapt to the new fluent config scheme

Update rector to 0.19

---

phpstan-baseline.neon
src/Module/Api/Json4_Data.php
src/Module/Api/Json5_Data.php
src/Module/Api/Json_Data.php
src/Module/Api/Method/Api4/PodcastEpisodes4Method.php
src/Module/Api/Method/Api5/DeletedPodcastEpisodes5Method.php
src/Module/Api/Method/Api5/PodcastEpisodes5Method.php
src/Module/Api/Method/DeletedPodcastEpisodesMethod.php
src/Module/Api/Method/PodcastEpisodesMethod.php
src/Module/Api/Subsonic_Xml_Data.php
src/Module/Api/Upnp_Api.php
src/Module/Api/Xml4_Data.php
src/Module/Api/Xml5_Data.php
src/Module/Api/Xml_Data.php
src/Module/Application/Podcast/ShowAction.php
src/Module/Podcast/PodcastDeleter.php
src/Module/Podcast/PodcastSyncer.php
src/Repository/DeletedPodcastEpisodeRepository.php
src/Repository/DeletedPodcastEpisodeRepositoryInterface.php
src/Repository/Model/Podcast.php
src/Repository/Model/Podcast_Episode.php
src/Repository/PodcastEpisodeRepository.php
src/Repository/PodcastEpisodeRepositoryInterface.php
src/Repository/PodcastRepository.php
src/Repository/service_definition.php
tests/Module/Api/Method/PodcastEpisodesMethodTest.php
tests/Module/Application/Podcast/ShowActionTest.php
tests/Repository/DeletedPodcastEpisodeRepositoryTest.php
tests/Repository/PodcastEpisodeRepositoryTest.php
tests/Repository/PodcastRepositoryTest.php

This prepares the repositories for some generalization

Split up podcast-related repositories

---

src/Module/Application/Admin/Access/AddHostAction.php
src/Module/Application/Admin/Access/UpdateRecordAction.php
src/Module/Application/Admin/Catalog/AddCatalogAction.php
src/Module/Application/Admin/Catalog/DeleteCatalogAction.php
src/Module/Application/Admin/Filter/AddFilterAction.php
src/Module/Application/Admin/Filter/UpdateFilterAction.php
src/Module/Application/Admin/User/AddUserAction.php
src/Module/Application/Admin/User/UpdateUserAction.php
src/Module/Application/DemocraticPlayback/CreateAction.php
src/Module/Application/Label/AddLabelAction.php
src/Module/Application/Podcast/CreateAction.php
src/Module/Application/Preferences/AdminUpdatePreferencesAction.php
src/Module/Application/Preferences/UpdatePreferencesAction.php
src/Module/Application/Preferences/UpdateUserAction.php
src/Module/Application/Radio/CreateAction.php
src/Module/Application/Share/CreateAction.php
src/Module/System/Core.php
src/Module/Util/RequestParser.php
tests/Module/Util/RequestParserTest.php

Also update the string getting logged and add tests

Replace all remaining usages of Core::verify_form by RequestParser

---

src/Repository/Model/Democratic.php

This makes democratic playlist creation work again

Define defaults for democratic playlist properties

---

phpstan-baseline.neon
src/Module/Api/Json5_Data.php
src/Module/Api/Json_Data.php
src/Module/Api/Method/Api5/BookmarkDelete5Method.php
src/Module/Api/Method/Api5/Bookmarks5Method.php
src/Module/Api/Method/BookmarkDeleteMethod.php
src/Module/Api/Method/BookmarkMethod.php
src/Module/Api/Method/BookmarksMethod.php
src/Module/Api/Subsonic_Api.php
src/Module/Api/Subsonic_Xml_Data.php
src/Module/Api/Xml5_Data.php
src/Module/Api/Xml_Data.php
src/Repository/BookmarkRepository.php
src/Repository/BookmarkRepositoryInterface.php
src/Repository/Model/Bookmark.php
src/Repository/Model/Catalog.php
tests/Repository/BookmarkRepositoryTest.php

Also perform some minor refactoring

Add tests for BookmarkRepository

---

phpstan-baseline.neon
public/templates/show_missing_albums.inc.php
public/templates/show_wanted_album_row.inc.php
public/templates/show_wanted_albums.inc.php
src/Application/Api/Ajax/Handler/IndexAjaxHandler.php
src/Module/Application/Album/ShowMissingAction.php
src/Module/Catalog/GarbageCollector/CatalogGarbageCollector.php
src/Repository/Model/Catalog.php
src/Repository/Model/Song.php
src/Repository/Model/Wanted.php
src/Repository/WantedRepository.php
src/Repository/WantedRepositoryInterface.php
tests/Repository/WantedRepositoryTest.php

- Standardize method-names
- Move query-methos into the Repo
- Some UI-Stuff...

Prepare the WantedRepository to extend BaseRepository

---

composer.json
composer_old.json
phpstan-baseline.neon
src/Config/service_definition.php
src/Module/Application/Artist/ShowMissingAction.php
src/Module/System/Cache/ArrayCacheDriver.php
src/Module/Wanted/MissingArtistFromMusicBrainzRetriever.php
src/Module/Wanted/MissingArtistRetrieverInterface.php
src/Repository/Model/Song_Preview.php
src/Repository/Model/Wanted.php
tests/Module/System/Cache/ArrayCacheDriverTest.php
tests/Module/Wanted/MissingArtistFromMusicBrainzRetrieverTest.php

This also introduces the psr simple-cache which will enable better caching in the future

Extract missing-artist retrieval from Wanted

---

src/Module/Catalog/Catalog_Seafile.php
src/Module/Catalog/Catalog_dropbox.php
src/Module/Catalog/Catalog_local.php
src/Module/Cli/PrintTagsCommand.php
src/Module/Song/SongSorter.php
src/Repository/Model/Catalog.php

Align Catalog properties types to the database columns

---

src/Config/ConfigurationKeyEnum.php
src/Module/Album/Deletion/AlbumDeleter.php
src/Module/Application/Art/ClearArtAction.php
src/Module/Art/ArtCleanup.php
src/Module/Art/ArtCleanupInterface.php
src/Module/Artist/Deletion/ArtistDeleter.php
src/Module/Catalog/GarbageCollector/CatalogGarbageCollector.php
src/Module/Label/Deletion/LabelDeleter.php
src/Module/Song/Deletion/SongDeleter.php
src/Repository/ImageRepository.php
src/Repository/Model/Art.php
src/Repository/Model/TVShow_Season.php
src/Repository/Model/TvShow.php
src/Repository/Model/Video.php

Let's start slowly to shed some light on this...

Extract cleanup methods from Art-class

---

composer.json
composer.lock
src/Module/Application/TvShowSeason/ConfirmDeleteAction.php

Remove some direct dependencies and update dropbox-php-sdk

Further composer.json cleanup

---

phpstan-baseline.neon
src/Module/Podcast/PodcastSyncer.php
src/Repository/Model/Podcast_Episode.php
src/Repository/PodcastEpisodeRepository.php
src/Repository/PodcastEpisodeRepositoryInterface.php
tests/Repository/PodcastEpisodeRepositoryTest.php

Also add new recent introduced type-issues from upstream to the ignore file. I'm sure, they wil be resolved soon :o)

Let Podcast_Episode::update_state use the new enum

---

src/Repository/UserActivityRepository.php

Those tables dont exist anymore...

Remove genre and stream from useractivity deletion

---

public/templates/show_search_bar.inc.php
public/themes/reborn/templates/dark.css
public/themes/reborn/templates/default.css
public/themes/reborn/templates/light.css

- Uniform height, font size and alignment of header elements
- Form control accent color takes on theme hue (see 'Random' checkbox)
- Dark mode form controls are now dark 🕶
Before
After
Before
After

Align header elements; improve light/dark form controls

---

src/Module/Application/Admin/Catalog/ShowDisabledAction.php

Correct misspelled variable-name

---

composer.lock
public/templates/show_disabled_songs.inc.php
src/Gui/Song/SongViewAdapter.php
src/Module/Api/Upnp_Api.php
src/Module/Application/Admin/Catalog/ShowDisabledAction.php
src/Module/Catalog/Export/CsvExporter.php
src/Module/Catalog/Export/ItunesExporter.php
src/Repository/Model/Song.php
src/Repository/SongRepository.php
src/Repository/SongRepositoryInterface.php
tests/Module/Application/Admin/Catalog/ShowDisabledActionTest.php

Also update the dependencies and perform some code optmizations

Add tests for the disabled-songs action

---

composer.lock
src/Module/Application/Image/ShowAction.php
src/Module/Application/Share/CreateAction.php
src/Module/Application/Stats/AbstractGraphRendererAction.php
src/Module/Application/Stats/GraphAction.php
src/Module/Application/Stats/ShowAction.php
src/Module/User/Activity/UserActivityRenderer.php

Replace some ObjectTypeToClassNameMapper::map calls

---

src/Application/Api/Ajax/Handler/TagAjaxHandler.php

I didn't find any usages of those action...

Remove some code related to tag management via ajx

---

public/templates/show_playlist_media_row.inc.php
public/templates/show_podcast_episode.inc.php
public/templates/show_podcast_episode_row.inc.php

Some browser convert successfully, but crawlers aren't

Some link are generated with &amp; instead of &

---

src/Repository/Model/Song.php

Fix display license

---

phpstan-baseline.neon
public/image.php
src/Config/ConfigurationKeyEnum.php
src/Module/Application/Image/AbstractShowAction.php
src/Module/Application/Image/ShowUserAvatarAction.php
src/Module/Application/service_definition.php
src/Repository/Model/User.php

Separate image loading for users and library-items

---

src/Module/Application/Rss/ShowAction.php
src/Module/Statistics/Stats.php
src/Module/Util/Rss/RssFeedTypeFactory.php
src/Module/Util/Rss/RssFeedTypeFactoryInterface.php
src/Module/Util/Rss/Surrogate/PlayableItemRssItemAdapter.php
src/Module/Util/Rss/Type/LatestAlbumFeed.php
src/Module/Util/Rss/Type/LatestArtistFeed.php
src/Module/Util/Rss/Type/LibraryItemFeed.php
src/Module/Util/Rss/Type/RecentlyPlayedFeed.php

Use null instead of some magic user with a negative id

Simplify rss handling for non-existing users

---

src/Module/Playback/Stream_Playlist.php

Sometimes parameters are missing, must handle it.
Example : poorly generated url like https://FQDN/stream.php?action=download&amp;song_id=36849

Add some check in media_to_url()

---

phpstan-baseline.neon
src/Module/Api/Xml_Data.php
src/Module/Application/Batch/DefaultAction.php
src/Module/Util/ZipHandler.php
src/Module/Util/ZipHandlerInterface.php
src/Repository/Model/Playlist.php
src/Repository/Model/Search.php
src/Repository/Model/playlist_object.php

Re-arrange some code in the ZipHandler and Batch action

---

package.json
src/js/tools.js

Explicity use 'window' as 'this' no longer refers to it

---

docs/CHANGELOG.md
resources/sql/ampache.sql
src/Module/System/Update/Migration/V6/Migration600071.php
src/Module/System/Update/Versions.php

Fix  #3954 - Add indexes to object_count

---

public/templates/show_form_search.inc.php

This patch add a permalink, so people can bookmark a search or share it with a link.

Add a permalink in the search form

---

public/templates/js_globals.php
src/js/base.js

Extract php strings from context menu

---

package.json
public/templates/scripts.inc.php
src/Module/Util/Environment.php

Use vite port 5177 to avoid conflicts with other projects running simultaneously

Use vite port 5177

---

public/templates/stylesheets.inc.php

I'm not sure everything is still in use but it will help us to override default style without dummy higher selector specificity.

CSS load reordering

---

src/Module/Api/Subsonic_Xml_Data.php

OpenSubsonic API non compliant with specification

---

src/Module/Api/Ajax.php
src/js/ajax.js

Use id attribute selector as workaround for multiple identical IDs

---

resources/templates/rss/generic_rss_feed.xml
src/Module/Util/Rss/Type/AbstractGenericRssFeed.php
src/Module/Util/Rss/Type/LatestAlbumFeed.php
src/Module/Util/Rss/Type/LatestShoutFeed.php

- datetime are now RFC2822
- atom selflinkd added
Cf https://github.com/ampache/ampache/issues/4076

Fix for rss compliance

---

src/Module/Util/Ui.php

Remove GLOB_BRACE
https://github.com/ampache/ampache/issues/4008

Fix GLOB_BRACE for some systems

---

.scrutinizer.yml

Scrutinizer build is fix, I saw that you and @usox worked on it in 2024
~~But, even if it build, it doesn't find any issue. I think some tuning is still necessary.~~ Fixed

Scrutinizer build fix

---

config/ampache.cfg.php.dist
src/Config/Init/InitializationHandlerConfig.php
src/Repository/Model/User.php

As mentioned in https://github.com/ampache/ampache/issues/3966 , actual captcha does not protect from actual spambot
I added those lines a few weeks ago and most of spam user creation are now blocked.
I share it, but I would understand you don't want that in the main branch :)

Check some spambot feature in user creation

---

src/Module/Application/Art/UploadArtAction.php
src/Module/Catalog/Catalog_subsonic.php
src/Repository/Model/Art.php
src/Repository/Model/Catalog.php
src/Repository/Model/User.php

Help to find error for Art upload
Cf https://github.com/ampache/ampache/issues/4199

Add error msg for Art upload

---

index.php
public/templates/error_page.inc.php
public/templates/install_header.inc.php
public/templates/show_denied.inc.php
public/templates/show_denied_permission.inc.php
public/templates/show_test.inc.php
public/templates/show_test_config.inc.php
public/templates/test_error_page.inc.php
resources/templates/update.xhtml

causes 404
/install.php, /index.php ...

remove loading of non existent bootstreap theme css

---

src/Module/Api/OpenSubsonic_Api.php
src/Module/Api/Subsonic_Api.php

Fixing maxBitRate conversion from Subsonic to stream proxy

---

src/Module/Api/OpenSubsonic_Api.php
src/Module/Api/Subsonic_Api.php

Ampache 7.7.1 and [Dsub 5.5.3 ](https://f-droid.org/fr/packages/github.daneren2005.dsub/)
When playing an album, I can share a Song but got an error when sharing an album ("Failed to create share  %s The requested data was not found")
This is a fix.

Fix share album on Subsonic API
